### ISSUE TITLE
Standard display resolution modes

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#104]
Currently, we have a reading mode button for birds, which zooms in on a specific time duration (maybe 1 min?), plays back the sound, and enables continuous playback. We need something similar for bats.

However,  actually, I realised it would be best to replace the reading button with another button that will display a particular resolution density that depends on the current spectrogram width.
Next to it, there should be a drop-down menu giving a choice of recommended display resolutions for the spectrograns: 1 min per 870 pix (the current spectrogram width) for birds, 10 s for 870 pix for bats, and one empty field for a custom resolution density.

These resolution densities are important to ensure that we have a standard "sampling frequency" (by humans of the sound recordings).

This should be future-proof for the upcoming automatic adjustment of spectrogram size to different screens.

**Comment by kdarras** [comment]
The zooming is working but even though the play button is transformed into a pause button, no audio is played back automatically anymore, and the cursor is not moving.
It would be nice to make clear graphically that the new drop-down button belongs to the reading mode button (maybe with a line separator).
please replace "Others" with "custom"

**Comment by kdarras** [comment]
unfortunately in the latest projects-time-frequency-space branch, this function is missing altogether

**Comment by kdarras** [comment]
unfortunately the drop-down menus for selecting bird/bat/custom visualisation densities are gone from the projects-time-frequency-space branch:


![Image](https://user-images.githubusercontent.com/7696198/197577398-f8b039e1-060a-421c-9b4a-57b50a2470af.png)

I can only see the CD icon

**Comment by LiuDilongNJ** [comment]
Click it

**Comment by kdarras** [comment]
Oh... I see.
However

- playback still does not start automatically
- the zoomed-in part of the spectrogram was always 10 s and not 60 s for birds or the chosen custom value (but this does not matter anymore since spectrgram sizes are flexible now, see below)
- "customs" should be replaced with "custom" :)
- now that flexible spectrogram sizes have been implemented, we need to display a proper resolution density (px/s) instead of a number of seconds. For birds: 1 min per 870 pix = 15 px/s. For bats: 10 s for 870 pix = 90 px/s
- it is a bit unclear that the user should click "custom" to activate the value the user just entered

Note that I inverted the units because I think it is more intuitive like that (edited first post accordingly).

**Comment by kdarras** [comment]
summarising insights from wechat conversation after testing latest branch:

- apparently, autoplay needs to be enabled in FF for the playback to start automatically. However, this is not required on the production server with the old code and the same FF version
- The caption of the pop-up should read: "zoom into and play back"
- little black right-pointing triangles in front of each menu option could help to clarify that when the user clicks these options, something will happen (the zooming and playback)

**Comment by kdarras** [comment]
working in Docker
