### ISSUE TITLE
Warning for sounds >192kHz sampling frequency in Firefox

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#107]
EDIT:

1. Let's remove the quick fix block that was introduced (see screenshot below) so that Chrome can play back the files that have up to 384 kHz sampling frequency
2. let's display a warning for Firefox users every time they open a file >192 kHz that cannot be played back: "Firefox cannot playback files with sampling frequencies > 192 kHz. Please switch to another browser such as Chrome." 

OBSOLETE:
Currently, Firefox and Chrome cannot play back frequencies above 96kHz (from recordings with sampling frequencies above 192 kHz). It would be good to have a notification every time a recording is opened that has a frequency above 96 kHz (= a sampling frequency above 192 kHz) so users stop wondering why they cannot hear the sounds above 96 kHz even with the slowest playback rate of 0.05.
The message could read: "Your browser cannot play back sounds sampled higher than 192 kHz. Sounds above 96 kHz cannot be heard, even with slow playback speed."
Note that the sampling frequency is written inside the recording table @LiuDilongNJ

**Comment by LiuDilongNJ** [comment]
I found that only Firefox can't play the audio above 192kHz. Because it only supports the audio from 8000-192000 rate. So it will report the error..
![image](https://user-images.githubusercontent.com/109188679/190047910-90584ed4-a85b-41ee-8411-9de76d3f97e4.png)
In September 2020, Noemi Perez uploaded the following code and the value of frequency was forced to be modified. Although it solved the playback problem in Firefox, it also prevents other browsers from playing audio above 96 kHz (actually other browsers would be able to play the audio above 96 kHz normally without this code.)
![image](https://user-images.githubusercontent.com/109188679/190047948-a9f84685-852e-451a-b715-36922b1e2df1.png)

**Comment by kdarras** [comment]
What happens if we remove this quick fix block? Can files >192 kHz sampling frequency not be played back at all in Firefox & Safari, or do they playback a 384 kHz file at 192 kHz?
What is the maximum supported sampling frequency for playback in Chrome and Safari?

**Comment by LiuDilongNJ** [comment]
Files >192 kHz sampling frequency not be played back at all in Firefox & Safari.
First determine which browser it is, and then solve the problem by situation.
8kHz < Firefox < 192kHz.
Chrome the maximum value tested so far is 384kHz

**Comment by LiuDilongNJ** [comment]
Files >192 kHz sampling frequency not be played back at all in Firefox & Safari.
First determine which browser it is, and then solve the problem by situation.
8kHz < Firefox < 192kHz.
Chrome the maximum value tested so far is 384kHz

**Comment by kdarras** [comment]
Excellent, so let's remove the quick fix block that you found screen-shot above so that Chrome can play back the files that have up to 384 kHz sampling frequency, and let's display a warning for Firefox users every time they open a file >192 kHz that cannot be played back: "Firefox cannot playback files with sampling frequencies > 192 kHz. Please switch to another browser such as Chrome." I updated the first post here and the title accordingly.

**Comment by kdarras** [comment]
in the branch 194-user-search-box-in-admin-interface-propagate-to-other-pages, all sounds above 18 kHz are filtered out.

Even though the overview spectrogram (small thumbnail and large image) are correctly showing all the sounds at all frequencies that are inside the 384 kHz sampling frequency file found [here](https://ecosound-web.uni-goettingen.de/ecosound_web/recording/show/1400), whenever we zoom, some filtering seems to be applied so that we can only see a black spectrogram above 18 kHz and not hear anything at normal or slow playback speeds.

**Comment by kdarras** [comment]
working in Docker
