### ISSUE TITLE
extracting FMaxE from selection

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#108]
add a button to analyse the current audio selection and find the frequency at which the sound is the loudest.

The button should extract the Y coordinates (or frequency bin range) of the point in the selection's spectrogram that has the highest amplitude peak and copy it to the clipboard. It should show an info message to indicate "Frequency of maximum energy: X kHz (copied to clipboard)"

**Comment by kdarras** [comment]
it seems to work but we need a space before the bracket, and in my case, the value was not copied to the clipboard

**Comment by kdarras** [comment]
It works :)
please only copy the number to the clipboard

**Comment by kdarras** [comment]
working in Docker

**Comment by kdarras** [comment]
a weird example of when the sound analysis did not work:


![Image](https://user-images.githubusercontent.com/7696198/198251935-5a07067f-d466-4b5f-a638-73045f72da85.png)

tested both in FF and Chrome, same result

**Comment by kdarras** [comment]
The results seems to be approximately correct, but I always find weird positive or negative offsets fro mthe true value that is visible on the spectrogram, example:
![image](https://user-images.githubusercontent.com/7696198/199955165-f7e6cce0-de07-4724-bcd7-7c0464ba3de6.png)

**Comment by LiuDilongNJ** [comment]
Is it possible that there is a maximum value in the Y coordinate of the image display but it is difficult to distinguish with the naked eye?When keeping MaxF and MinF constant, and narrowing the range of MinTime and MaxTime, it will show around 78000 which is in the right place. In fact there is an offset indeedly, but not too much.  For a 96,000Hz audio file, the maximum offset is 375 when the FFT is 512 while the maximum offset is 750 when the FFT is 128. 
Let me know if we need to display both time and FMaxE when the button is clicked.
![image](https://user-images.githubusercontent.com/109188679/200097084-4263bcb9-63ed-4ce1-9d46-3a5da75b4248.png)

**Comment by kdarras** [comment]
No, the spectrogram should show quite clearly with the most vivid color where the FMaxE is. Hard to miss with the naked eye. Noise is usually much quieter.

Alright, it would indeed be helpful to copy both the absolute time and the max Frequency to the clipboard so we know exactly where that value comes from. (Or maybe would it be useful to automatically make a selection at these coordinates for debugging?)

I also confirmed by opening the recording in Audacity that the frequency values shown in the text boxes under the spectrogram are matching those shown in Audacity:
![image](https://user-images.githubusercontent.com/7696198/200301831-26570b5f-cb3c-421c-b1bf-e13657d8debe.png)
![image](https://user-images.githubusercontent.com/7696198/200302943-8803fe92-6789-488a-be89-cb024b553095.png)

The offset is indeed quite small but quite real and puzzling. When you look at the spectrogram above, you can see the offset is not caused by too large bins, and there is clearly no max at 79103 Hz. The problem is that this measure must be very accurate as bat experts use it to identify the detected individuals.

**Comment by kdarras** [comment]
actually, I am starting to think that since the coordinate export tool (right next to the peak finder) works on the current selection, maybe the peak finding tool should also do that... I can create a new issue if you think it makes sense

**Comment by LiuDilongNJ** [comment]
I see, I'll keep revising it so it's accurate.

**Comment by kdarras** [comment]
It looks like it takes longer to compute now but it's fine, since it is accurate now:
![image](https://user-images.githubusercontent.com/7696198/200795488-77aa9fde-3ab8-4427-914b-e102729c0485.png)
![image](https://user-images.githubusercontent.com/7696198/200795405-45a0c590-dc71-4337-af10-b9a26d4f2bac.png)
After re-trying the first measurement, it successfully copied data to the clipboard. I will monitor how often this happens.
