### ISSUE TITLE
managing project permissions in admin interface

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#116]
in the admin interface, admins can currently set access to collections for all users:
![Image](https://user-images.githubusercontent.com/7696198/185346602-c22df0ee-85c7-4f84-9151-fa3a5f42dc3f.png)
and project managers can do this for the users of the projects that they manage.

We need to expand this existing feature by grouping collections under projects (using collapsible arrows)
Admins would see all projects and project managers only the projects assigned to them (by admins).

**Comment by kdarras** [comment]
very nice implementation, but the window size needs to adapt:
![Image](https://user-images.githubusercontent.com/7696198/195376353-e97a93a9-fb8c-4c3c-9095-9448f46d5e32.png)

**Comment by kdarras** [comment]
working in Docker

**Comment by kdarras** [comment]
I noticed just now that the part "project managers can do this [manage users} for the users of the projects that they manage" is not working:
![image](https://user-images.githubusercontent.com/7696198/209090752-baebbbc8-2008-4fd6-9085-205a930e50a3.png)

Here, all users were created by the admin, but only "New User 2" has access to the project manager's project.However, the project manager can manage him too.

Project managers should only be able to manage the users who can access their managed projects.
I am not sure when this problem appeared (which was part of the last task), but I noticed this in the latest version that I am testing. Let me know how to proceed @LiuDilongNJ

**Comment by LiuDilongNJ** [comment]
If project managers can only manage users who have access to the projects. Then the project manager will not be able to add permissions for new users. Please let me know if I should modify it under this situation.

**Comment by kdarras** [comment]
Oh, right, good point, I did not notice this logical inconsistency.

After thinking more about it: I confirm that project managers should only be able to manage the users who can access their managed projects. It means admins will be required to add existing users to the projects of the project managers. I means project managers can only add the new users that they create to their projects. It means project managers cannot re-assign users to their projects after de-assigning them (they need to ask the admin).

It is important from a privacy point of view that not too many people (only admins) have access to personal data (names, email addresses) of the users, and we will implement a better privacy management later.

**Comment by kdarras** [comment]
working, forgot to close
