### ISSUE TITLE
Sharing link for tags

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#131]
Previously, it was possible to enter the coordinates (in time and frequency, with t_min, t_max, f_min, f_max) into the URL to zoom directly into a specific part of the spectrogram.
This has changed and it is impossible to do this now. As a result, it is also impossible to share specific parts of a recording with colleagues for collaborative work.

We need a sharing button inside the tag window, for generating (and copying to the clipboard, with a message " Sharing link copied to clipboard") a "tag sharing link" that we can send to colleagues. It could be placed next to the creation user info in the tag window:
![image](https://user-images.githubusercontent.com/7696198/187062989-e61be132-c613-4b39-a6cd-5a916f04ce7b.png)

**Comment by LiuDilongNJ** [comment]
There are many parameters on the recording page and it is safe to request them via post. I think that would be great to have get (passing only four coordinates) and post requests at the same time. It looks very user-friendly

**Comment by kdarras** [comment]
If you think that there are no disadvantages to this method, then we can implement it back. I will try to ask Noemi.

**Comment by LiuDilongNJ** [comment]
There are many parameters on the recording page and it is safe to request them via post. I think that would be great to have get (passing only four coordinates) and post requests at the same time. It very user-friendly.

**Comment by kdarras** [comment]
Agreed, let's do it!

**Comment by kdarras** [comment]
works in Docker. Please write "URL" instead or "Url" @LiuDilongNJ
