### ISSUE TITLE
open zoomed-in tag in new tab

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#141]
It would be nice, when pressing the Ctrl key, that the zoom into tag button (that appears when you click on a tag) opens the tag in another tab.

**Comment by LiuDilongNJ** [comment]
I'm afraid that I cannot implement the function by clicking the button Ctrl due to the key conflict. It can open link but cannot be in the new tab. Can we change for the button Alt?

**Comment by kdarras** [comment]
Using Alt is also fine. Would be be possible to have some info like "+Alt: open in new tab" when hovering above that button?

**Comment by kdarras** [comment]
working in docker
