### ISSUE TITLE
timeline collection view

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#157]
implement the timeline view as an overview of recordings in a collection:

- have a new button next to the list and gallery view buttons
- Group recordings in rows according to site
- place recordings according to their start and end time on a time axis that goes from the earliest to the latest point in time, using boxes named after the recordings as placeholders
- clicking recordings opens them in the usual spectrogram viewer

**Comment by LiuDilongNJ** [comment]
1. Is this a horizontal timeline?
2. according to the site classification, like the picture, each site has a timeline or all sites share a common timeline?
3. It would be even better if you have a reference style, otherwise I will design it for you.
![image](https://user-images.githubusercontent.com/109188679/204461812-3ec6977e-f168-4659-86ea-14c7e3625d65.png)
![image](https://user-images.githubusercontent.com/109188679/204462048-420c8cbd-fc6b-4ac6-9c33-e91dc08b8400.png)

**Comment by kdarras** [comment]
Hi Dilong, the second design you proposed is appropriate, but I sketched a design here:
![image](https://user-images.githubusercontent.com/7696198/204472258-b6356fce-4d92-41ba-9c7f-7df39ee6fd6c.png)
Note that recording placeholders can have different widths, according to the durations of the recordings.

Then, to adapt the width of the timeline to different display sizes, we either have 1) a horizontal scrollbar as you suggested to keep the width of the timeline constant, OR we resize the timeline when the window is resized (better, but may rather be related to issue #148 )

**Comment by LiuDilongNJ** [comment]
I have implemented this function but there is no zooming button at the moment. When the zooming is completed, you will see that.

**Comment by kdarras** [comment]
Yes, but will it be possible to display the spectrograms inside the timeline ( https://github.com/ecomontec/ecoSound-web/issues/202 ) instead of above them?

**Comment by LiuDilongNJ** [comment]
Yes

**Comment by LiuDilongNJ** [comment]
Yes, I can do that

**Comment by kdarras** [comment]
excellent.

**Comment by kdarras** [comment]
bug when setting default collection view to "timeline" when saving new collection:
![image](https://user-images.githubusercontent.com/7696198/208094219-3988dad9-18d3-4bbd-9dbd-f998af3c9d09.png)

**Comment by kdarras** [comment]
I see you already implemented zooming as per #148 , very nice.
However, is it possible to display the image inside the timeline, instead of above? This is what I meant with the previous questions. Also, please insert the spectrograms with both start and end times, just like here:
![image](https://user-images.githubusercontent.com/7696198/208100976-aa572b76-f733-4413-935d-69dc7856b87b.png)
not just a starting time.

**Comment by LiuDilongNJ** [comment]
I uploaded a sound clip which starts at 10am and ends at 10:05am.
![image](https://user-images.githubusercontent.com/109188679/208332806-75af159b-da18-491d-8a42-eef6e323f8e0.png)
![image](https://user-images.githubusercontent.com/109188679/208332847-66c5aa56-d113-439f-92be-e4a435becf12.png)

**Comment by kdarras** [comment]
Excellent, looking forward to this new funciton.

PS: In the version that I tested above, the spectrograms looked like that:
![image](https://user-images.githubusercontent.com/7696198/208397920-3e7534de-a078-477f-aebc-a77929decfa1.png)

**Comment by LiuDilongNJ** [comment]
That is because the audio file is too short or the upload interval between the two audio files is too long causing the span between the two files on the timeline to be too wide, so in this case a spectrogram with the minimum length will be displayed.

If the minimum length spectrogram is displayed, when we select it, we can see the start and end points on the timeline. As shown in the pic below.

![image](https://user-images.githubusercontent.com/109188679/208652981-37153f3a-d7d3-47e9-91a9-c29a014135ee.png)

**Comment by kdarras** [comment]
working in Docker. However, it would be good to open the timeline at a zoom level where all recordings are visible by default (just like the maps)

**Comment by kdarras** [comment]
The timeline view is empty when opening collections where timeline is defined as the default view. It appears only when switchign back from the other collection views.
![image](https://user-images.githubusercontent.com/7696198/210215423-07a03868-d35b-4ece-851e-5dd257d798ac.png)

**Comment by kdarras** [comment]
working in Docker

**Comment by kdarras** [comment]
the spectrograms are not visible when the map is collapsed:
![image](https://user-images.githubusercontent.com/7696198/211858035-f3b0ef10-af0d-4a3a-9e23-f44f2c6d3fd4.png)

**Comment by kdarras** [comment]
further alignment problem:
![image](https://user-images.githubusercontent.com/7696198/211865509-bad4f239-fa83-48d1-9fee-598f1d6b4c76.png)

**Comment by kdarras** [comment]
working in production
