### ISSUE TITLE
automatic resizing and generation of spectrogram

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#159]
The spectrogram should adapt and fill the screen.

additional information added on 12 Oct:

1. solution: during the insertion into the database, additional spectrogram sizes are generated for different screen sizes (maybe 3 standard sizes)
2. solution (preferred): automatic and flexible spectrogram generation depending on the user's screen resolution

If the overview (big) spectrogram generation is fast enough, maybe the only spectrograms that need to be generated after addign new recordings to the database are those for the thumbnails, which are displayed at the same size in all devices.

**Comment by kdarras** [comment]
Interestingly, this was fixed as soon as I created the first tag and reloaded the page...

**Comment by LiuDilongNJ** [comment]
Please try again, maybe because of the cache

**Comment by kdarras** [comment]
working in Docker
