### ISSUE TITLE
Audio files in MP3 format cannot be uploaded to Recordings

### ISSUE THREAD

**Issue by LiuDilongNJ** [ecomontec/ecoSound-web#190]
When I upload an MP3, it showed "success".

![微信截图_20220816145555](https://user-images.githubusercontent.com/109188679/184816919-6d75a2f1-a1be-44f0-8929-e24996a3fbcd.png)

But the error is reported in the mysql database file_upload table.

![微信截图_20220816145623](https://user-images.githubusercontent.com/109188679/184816925-c1eac523-9128-4c7b-a982-e76389d32972.png)

**Comment by kdarras** [comment]
fixed
