### ISSUE TITLE
Selection of call type cannot be saved

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#191]
The selection and edition of the call type cannot be applied, so that it always returns to the first value in the drop-down menu:
![image](https://user-images.githubusercontent.com/7696198/185070577-9883ce91-a95a-4bf5-a80c-1d9a733c0015.png)
UPDATE 10 Sep: please make sure that there is also a blank entry in the drop-down menu, as this field does not need to be filled.

**Comment by kdarras** [comment]
I can only test this on production as there are no proper species data in the local version

**Comment by kdarras** [comment]
Call types drop-down list is empty

**Comment by LiuDilongNJ** [comment]
![image](https://user-images.githubusercontent.com/109188679/192073530-9fd9acf4-d82e-49e4-a490-919cf076b7a6.png)
Testing with Test primate will work fine
