### ISSUE TITLE
duty cycle for recordings

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#217]
We need a new field in the recordings tables called "duty cycle". It describes how many minutes of sound are recorded per period and it can be expressed as a fraction. For instance, 1/3 means 1 minute of sound is recorded every 3 minutes.
If it is better to store that information in two fields (this is likely), then we can call these duty_cycle_recording and duty_cycle_period.

The duty cycle is relevant only for meta-recordings, as with real recordings, the use of a duty cycle will result in separate files (shown with spectrograms #202 ).

Duty-cycled meta-recordings should be shown with banded bars in the timeline. The band color proportions should correspond to the duty cycle, and the duty cycle be included in the label.

**Comment by LiuDilongNJ** [comment]
How to show better .
1. Directly display the quarter
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/fc449132-3aee-4d61-9a5b-39b00d89cb4a)
2. Average 10 equal parts
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/cb60b289-0c47-4cd9-b398-7973ce5630a9)

**Comment by kdarras** [comment]
Good question. I prefer the banded one at the bottom - it emphasizes the periodicity better.

**Comment by kdarras** [comment]
Needed to add to the instructions:
- duty_cycle_recording (duration of duty-cycled recordings in minutes)
- duty_cycle_period (duration of cycle - recording + pause - in minutes)

**Comment by LiuDilongNJ** [comment]
There is a bug here, which causes the display to be incorrect.

**Comment by kdarras** [comment]
Display works now but these fields are not yet visible in the recordings table. By the way, it would make sense to add the recording type (metadata/audio) in there as well.
Note: I had an error when manually setting the date of one recording:
![image](https://github.com/user-attachments/assets/d0332e69-586c-4583-9eb8-c42976bdedf6)
It pops up as soon as I enter "0", even though I am not finished yet with typing. I suppose the date check should happen after shifting the focus to another field.

**Comment by kdarras** [comment]
this is what happens when I import the metadata.csv file that was previously working.
![Screenshot from 2024-08-16 12-27-17](https://github.com/user-attachments/assets/b4707583-e214-4dfb-872d-3a7df32f372c)


It contains:
recording_start,duration_s,sampling_rate,name,bit_rate,channel_number,duty_cycle_recording,duty_cycle_period
2020-01-01 00:00:00,600,44100,name1,16,2,1,3
2020-01-01 01:00:00,1200,48000,name2,16,1,1,10

However, the import worked and then, when I want to sort on data type, I get the error again:
![image](https://github.com/user-attachments/assets/6f2278b8-a30b-499d-af78-a654dfdfb45a)

**Comment by LiuDilongNJ** [comment]
I forgot to determine whether it was audio or metadata, which resulted in the metadata also executing the command to read ID3.

**Comment by kdarras** [comment]
Working in Docker.

**Comment by kdarras** [comment]
completed in #511
