### ISSUE TITLE
replace sensors with recorders and microphones

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#220]
Currently, we use one field called "sensor" to describe what equipment was used to record soundscapes. It combines the recorder and microphone information.
However, many recorders allow to plug in different microphones. We possibly need one table for recorders, and one table for the possible microphones that can be plugged in. Or: one table with all recorder-microphone combinations.

Then, when uploading recordings, the mask should have two input fields: the recorder drop-down menu and the microphone drop-down menu, which should be filtered by the possible values for the chosen sensor. The same should be applied to the recordings table as these fields should be put inside to be edited.

After this change, the input of the recorder and microphone should be mandatory for project managers uploading recordings, as we need to achieve standardisation of recordings (#241 ).

The tables should have the following structure:
recorders:
- id
- model
- version (optional)
- brand

microphones:
- id
- name
- microphone element (optional)
- sensitivity (negative integer)
- signal-to-noise ratio (positive integer)
However, this solution probably requires another table to list the possible recorder-microphone combinations?

Alternative structure for a single table:
- sensor_id
- recorder_id
- recorder_model
- recorder_version (optional)
- recorder_brand
- microphone_id
- microphone_name
- microphone_element (optional)
- microphone_sensitivity_dB (negative integer)
- microphone_SNR_dB (signal-to-noise ratio, positive integer)
However, this solution creates some redundancy, as multiple recorders can use the same microphone, and multiple microphones can use the same recorder.

Dilong already implemented this kind of hierarchical filtering with the IUCN GET (#179 )

**Comment by LiuDilongNJ** [comment]
![image](https://user-images.githubusercontent.com/109188679/204310069-e8648d94-ce9d-4561-8e1b-9964a7fccc8f.png)
Should we set the drop-down menu like the image?

![image](https://user-images.githubusercontent.com/109188679/204311581-3584bbd8-2d34-475b-a11b-d601ba10b361.png)
Do we preset a relationship that when I select sensor1, the record drop-down box can select record1,4,6 and the microphone drop-down box can select microphone2,3, When I select sensor5, the recorder dropdown box can select recorder5,7, microphone dropdown box can select microphone4,6, right?

**Comment by kdarras** [comment]
Thanks Dilong. There is a slight misunderstanding. So far, we used one field for the sensor, and it which combined the recorder and microphone information. Now, we should split the microphone and sensor information into two different fields. Together, they form a sensor ID. So: the user will not need to fill a sensor field anymore. First, the user will fill in the recorder information, and then, choose a microphone from the list of compatible microphones.

Before I give you the tables with the microphone and sensor combinations, do you confirm that the "alternative" table structure (see first post) is the one we need? You can have a look at typical recorder-microphone combinations here: https://docs.google.com/spreadsheets/d/1m6rAkWKYFHKKdl2K7vzpgDEbIDr5vthkb4goKTMVms0/edit#gid=0 (these are the ones we will use)

**Comment by LiuDilongNJ** [comment]
Got it. I think the first one is better.

**Comment by LiuDilongNJ** [comment]
Should we show all the recorders and microphones? Or, when I select Wildlife Acoustics branded recorders, I can then continue to select Wildlife Acoustics branded microphones.

**Comment by kdarras** [comment]
Alright Dilong, I can prepare the final recorder and microphone data. The microphones drop-down should be filtered so that only the microphones compatible with the chosen recorder are shown (just like the hierarchical IUCN GET ecosystem types).

**Comment by kdarras** [comment]
working in Docker.
Created new issue to display sensors in collection list view: #297 
I will send you a clean list of sensors and microphones by mail.

**Comment by kdarras** [comment]
please use the latest data sent by Frederik, as we still have invalid entries in the list:
![Screenshot from 2022-12-16 13-17-09](https://user-images.githubusercontent.com/7696198/208099423-bd397397-8b28-4c31-ad07-f00afcc41197.png)

**Comment by kdarras** [comment]
Freddy asks whether the recorder dropdown could also mention the brands? Maybe separated from the model like this "[model] | [brand]"

**Comment by kdarras** [comment]
Excellent, thanks Dilong!
