### ISSUE TITLE
new "sound" table

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#225]
Add a new "sound" table:

- sound_id
- phony (biophony, anthropophony, geophony, unknown)
- sound_type (text field with 30 characters max)

The table will be filled manually later by myself, as there is no established typology yet for sound types within phonies. It's a research project in itself.

The sound table should be linked to the tag table with the new "sound_id" field

**Comment by kdarras** [comment]
please insert some dummy values for sound_type so I can test this in relation to #268 . Correct typo "unknown"

**Comment by kdarras** [comment]
yes, we should show it. You could populate the table with a few entries:

- biophony: fish chorus, bat swarm, insect broadband noise
- anthropophony: transportation, human voices, mining
- geophony: wind, wave, earthquake, rain

**Comment by kdarras** [comment]
working in Docker except that the sound type field is optional.

**Comment by LiuDilongNJ** [comment]
Is sound type not allowed to be modified?

**Comment by kdarras** [comment]
working in Docker
