### ISSUE TITLE
spectrogram preview generation buggy

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#230]
The thumbnail generator has become really messy:
![image](https://user-images.githubusercontent.com/7696198/189517473-e776e517-c27f-4085-8735-07a330023233.png)

Different recordings get the same thumbnail, and some thumbnails are not generated. The underlying recordings are correct.

The screenshot above is from Worldwide Soundscapes project > Demonstration collection (https://ecosound-web.de/ecosound_web/collection/show/49).

Not just thumbnails, but also the spectrograms displayed when first opening a recording can be wrong (example: Round 1 newTree project https://ecosound-web.de/ecosound_web/collection/show/54) and it seems like it could happen to files with the same file name, but not always.

**Comment by LiuDilongNJ** [comment]
I already can not find the recordings with these names on the site. Can you tell me a few files that have the same thumbnail problem? I'll fix it.

**Comment by kdarras** [comment]
It seems my connection is too bad at the moment, but you will find these recordings inside the Worldwide Soundscapes project > Demonstration collection. Note that some thumbnails are missing, and others are simply duplicated/wrong. You will see when opening some files that the overview thumbnail does not correspond to the one generated when opening the entire file.

**Comment by LiuDilongNJ** [comment]
I fixed the thumbnails, please check. Also, regarding the spectrogram error that shows up when opening a recording for the first time, can you point out which recording it is?

**Comment by kdarras** [comment]
Excellent. This is hard to reproduce and did not occur in Docker locally if I recall correctly, so I will check this after the server deployment, together with a colleague who is doing a lot of uploads.
There are many files that had thumbnail problems. I wanted to show a few examples from the collections I mentioned before, but it seems that all the spectrograms were already fixed :+1:  What was the bug?

**Comment by LiuDilongNJ** [comment]
Some of the files for the spectrograms were lost on the server, so I regenerated them.
