### ISSUE TITLE
adjusting IUCN GET tables

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#236]
in the site table, we should rename functional_group_id to functional_type_id
the explore table should be renamed iucn_get, explore_id should be named iucn_get_id

**Comment by LiuDilongNJ** [comment]
Do I need to replace their names in the website?

**Comment by kdarras** [comment]
The names should be correct in the mySQL database. In the admin interface, the fields names are already correct.

**Comment by kdarras** [comment]
will check in phpmyadmin once on production
