### ISSUE TITLE
integrating input of temporal meta-data

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#240]
The vast majority of data in passive acoustic monitoring are never uploaded and rest on local storage media until they might be used at some future point. The simple fact that these data are usually not discoverable impairs their re-use, to the point that they might never be used at all.

We need to allow users to input meta-data about the temporal coverage and scope of soundscape recordings.

This should happen through the upload of a CSV listing recording starting date-times, durations, and sampling frequencies.

The simplest way (user point of view) of integrating these meta-data into the website could be to use the current tab for recordings. If CSVs are dragged onto it, their structure should be checked and rejected if invalid.

An info button "meta-data upload (?)" above the upload widget could be displayed with the following info on mouse over: "Recording temporal meta-data can be uploaded with a CSV containing the following columns: recording_start (format: YYYY-MM-DD HH:MM:SS, local time), duration_s (duration of recording in seconds), sampling_rate (numeric value in Hz), name (optional, limited to X characters), bit_rate (optional, integer), channel_number (optional, integer)"

The data would be inserted into the recordings table, with a new "data_type" field to distinguish between "meta-data" and "audio data". filename, filesize, filehash, license fields should be empty or NULL. The corresponding user, creation_datetime should be filled in automatically.

The corresponding "meta-recordings" would not require spectrogram generation but should be shown alongside real audio recordings inside the collections with a thumbnail called "meta-recording (no audio) - sampling rate: X" instead of a mini-spectrogram. Inside the recordings table in the admin interface, instead of the button to open a recording, a passive icon (maybe a crossed eye) could indicate that these are meta-data instead.

This feature makes most sense if #157 is implemented.

**Comment by LiuDilongNJ** [comment]
Does the uploaded csv only need to be filled with recording_start, duration_s and sampling_rate data? Do we need the 'name' field to distinguish the metadata?

**Comment by kdarras** [comment]
The uploaded csv needs *at least* recording_start, duration_s and sampling_rate fields, because all the other data can be edited in the table.
However, it would be nice to accept additional fields (such as the "name" field), yes, but only if that does not require more working time from you.

**Comment by LiuDilongNJ** [comment]
You can tell me all the other fields that might be used.

**Comment by kdarras** [comment]
OK, I edited the first post.

**Comment by kdarras** [comment]
A few issues:
-typos in the popup information: please write "channel" instead of "hannel", insert a space after "optional,". Please also remove "temporal" (my bad).
-the info should appear after clicking an info button ("?" or anything that is consistent with the previous buttons) in a real pop-up window, so that it stays visible and so that users can copy the column names to the table they will create.

The upload did not work for the following CSV file (error message: Failed to upload file.":
recording_start,duration_s,sampling_rate
2022-01-01 13:40:00,300,1000
2022-01-01 13:50:00,300,1000
2022-01-03 13:40:00,200,4000
2022-01-10 13:40:00,10000,20000

Since the other fields are optional and I believe I have written valid values, it should work with that file.

Then, I tried a complete CSV file, and the upload also failed:
recording_start,duration_s,sampling_rate,name,bit_rate,channel_number
2022-01-01 13:40:00,300,1000,test1,16,1
2022-01-01 13:50:00,300,1000,test2,16,1
2022-01-03 13:40:00,200,4000,test3,32,2
2022-01-10 13:40:00,10000,20000,test4,32,2

More informative error messages should be written, for instance:
-when a field name is found that does not match the required field names: "unrecognised field "X" found - aborted upload."
-when the values of recognised fields do not match the required format: "wrong format for field "X - aborted upload."

**Comment by kdarras** [comment]
very nice idea of yours to have a button for "download demo". However, it would be better to call it "download template".
Then, you could add a third button called "View instructions", because the users need to know the units and formats of the data that they will enter (I could not find these instructions). The rest is working as it should.

**Comment by kdarras** [comment]
Excellent.
Working in Docker.

 Can you add "You can download a template CSV file to fill in your data" to the instructions text?

**Comment by LiuDilongNJ** [comment]
I have fixed it, please test it again.

**Comment by kdarras** [comment]
It is not inside the instructions yet:
![image](https://user-images.githubusercontent.com/7696198/218418024-f01d8c94-1c86-4ced-8216-f7bb9b9c7242.png)

But you can add that text when deploying to production.

**Comment by LiuDilongNJ** [comment]
Got it.
