### ISSUE TITLE
multiple labels per recording

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#245]
Recordings sometimes need some manual quality control done by users.

We need to be able to label recordings with multiple labels to describe different aspects of recording quality. Only one label can be used per label type, as the labels within a label type are mutually exclusive.

This requires the addition of a label_type field to the labels table.

User interface: the "+" button can be removed. From now on, adding new label names into the labels table can only be done through the admin interface, as described in #234 .
The chosen labels can be shown under the "My label" text as usual, but one drop-down menu should appear for each label type. We can use different colors for the different types (a bit like GitHub).

These predefined label types should already exist in the table:

1. label type: recording quality. labels: technically successful/broadband noise/silent parts
2. label type: annotation status. labels: not analysed/tagged/reviewed

**Comment by LiuDilongNJ** [comment]
We still can only have one label for a recording?

**Comment by LiuDilongNJ** [comment]
1. A recording can have many labels.
2. Each recording initially has two labels, which are two drop-down selection boxes.
3. The name field of the new label is a text input box, and the type field has a fixed value
4. In the recording list page, do we want to show all the labels, or just the two initial labels.
5. Can the user modify and delete all the labels?
6. In the recording page, all labels are displayed, but no new labels can be added? The two initial labels can be modified via the drop-down selection box.
7. For 6, I think it would be better for the user to use the modal box on the recording page to edit the labels.

**Comment by kdarras** [comment]
clarified first post.
1. yes, as many labels as there are label types
2. yes
3. yes, but there are a few pre-existing labels and new custom labels can be added according to #234 
4. in the collection's list view, we should show all labels. Labels should be empty by default, at creation
5. yes.
6. yes. New labels can only be added in the admin interface according to #234 
7. OK, if you want we can keep the "+" icon but open the same modal box that would be used for #234 . Just let me know so that I edit the post accordingly.

**Comment by kdarras** [comment]
obsolete issue, replaced with more flexible #542
