### ISSUE TITLE
database consistency

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#247]
We need clarity to determine whether duplicate names and entries are allowed in the different tables of the database:

- projects: only unique names
- collections: only unique names within projects
- recordings: within collections, only unique recording files (as based on MD5 hash)
- user names: only unique names
- sites: unique names within projects

As remarked by Dilong, the GitHub database structure needs to be checked against the production server structure to find and resolve inconsistencies ( NULL allowed or not, etc.)

**Comment by kdarras** [comment]
After reviewing the current duplicates inside the database, it seems that we need to relax some rules to allow more flexibility for the users:

- recording "sound names" were introduced to allow the project managers to name them as they like, so we should not introduce any constraints (removed rule from first post)

**Comment by kdarras** [comment]
Regarding sites, Dilong mentioned that since the relationship between sites and projects is many-to-many, we can control the uniqueness of sites when creating and modifying them, but things become complicated when assigning a site to a project that contains a site with the same name.

Accordingly, we should remove the "site name uniqueness within projects" constraint, but prompt users instead when they create or edit a site whose name is already present in the project, and when they assign a site to a project that already has this site's name with: "Project [X] already contains a site with the same name." Options buttons: Cancel/Append site ID

**Comment by LiuDilongNJ** [comment]
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/bfbe54ff-d8d0-4bb3-9c62-9e02ec5c05c7)
I want to make sure about the append issue, user A appends user B's site, so will it cause the data to be messed up. I think the right way is to show the duplicate project like the picture, and then the user can check the site with the same name and modify it.

**Comment by kdarras** [comment]
Good point, thanks. Yes when creating sites and editing site names, it would be sufficient to show the warning:
 "Project [X] already contains a site named [Y]." Options buttons: Return to edit/Append site ID to name

When changing site assignments however, we need to show a warning next to the project like you did above. But the red text needs to be more clear, please write "Site named "[site name]" already exists". If the user proceeds to save these assignments, then we could show the warning written above.
What do you think?

**Comment by kdarras** [comment]
Note: sensor_id is a deprecated field in the "recording" table, as we have recorder_id and microphone_id now

**Comment by kdarras** [comment]
Note: I had to add a "source" column to the species table as we needed to distinguish previous entries form the IUCN from future entries for German insects obtained from another source.

**Comment by kdarras** [comment]
It seems that you reverted back to the original instructions and that on the version that I am testing in Docker right now, site names must be unique within projects.

This implementation is also OK and may be more simple, so I edited the first post to reflect the change back to the original plan.

However, we should be a bit more clear about the wording of the arning inside the assignments table: please write "Site name "[X]" already exists." Using these quotes, we emphasize that it is about the site name, and the users should intuitively understand that the solution is to give it another name.
