### ISSUE TITLE
combined drop-down menu with filtering text box

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#251]
To be able to deal with large numbers of items in all the current drop-down menus of the admin interface, we should convert all of these to text-searchable drop-down menus with a fixed height + scrollbar.

This way, we would combine the advantages of a drop-box (rapid overview and selection by mouse) and filtering (to narrow down the selection to the input text, especially for big lists).

The species selector in the tags window actually implements it nicely already. Think about where else this might be useful.

**Comment by kdarras** [comment]
Works nicely in Docker. Do you confirm that there is maximum, fixed height so that when there are many items, a scrollbar appears?

**Comment by LiuDilongNJ** [comment]
Currently it is based on the height of the window, do I need to set it to a fixed height?
![image](https://github.com/user-attachments/assets/1647a0c1-ce5b-46a1-ab0a-b9075e90d09d)

**Comment by kdarras** [comment]
Alright, it is good like that.

**Comment by kdarras** [comment]
Working in Docker

**Comment by kdarras** [comment]
working well online. Created #501 for alphabetical sorting

**Comment by kdarras** [comment]
completed in #511
