### ISSUE TITLE
refactoring tag window

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#268]
Because of the new structure with sound types and species, the window needs to have a flexible arrangement and content now.

First, tag creators should be prompted to input the tag's phony (see #225 ) and depending on this input, the sound type with drop-down menus (sound type needs to be filterable, like the species box).

The last phony input should be pre-selected for the next created tag (i.e., remembered with a cookie by the website).

The time and frequency fields, as well as the comments box should always be visible in the window.

If "biophony" is selected, species, individuals, call distance, animal_sound_type, Google Image and Xeno-Canto links, should be shown.

If "geophony", "anthropophony" or "unknown" are selected, the biophony-specific fields should not be shown. It is likely that we will find out only later what phony-specific fields could be shown conditionally.

**Comment by kdarras** [comment]
Dilong noted elsewhere that having one table with some fields that are conditionally NULL is preferable.

**Comment by kdarras** [comment]
Note that it should not be possible to fill in a distance directly during tag creation:
![image](https://user-images.githubusercontent.com/7696198/201626907-3e83d12e-7642-49ba-ad37-4b3ee52220b0.png)
This part was previously inactivated. Call distances should only be allowed to fill after clicking the dedicated button so that the right conditions are met (full-spectrum playback and visualization), otherwise the estimates can be biased:
![image](https://user-images.githubusercontent.com/7696198/201627059-0580fc3c-fc7a-44a9-ba3e-c964f7a5fb0f.png)

**Comment by kdarras** [comment]
I forgot to mention that "number of individuals" should appear only for the biophony (clarified in first post). It should also be renamed to "individuals" simply. Please correct the typo "unknow":
![image](https://user-images.githubusercontent.com/7696198/206732628-1a8813de-8e7c-4c97-919d-933d59883cb6.png)
we need some dummy sound_type values to check whether the second drop-down menu for sound type appears (it is an optional field).
Reminder: it must not be possible to fill in the sound distance from the tag creation window, you can gray out and lock that field, like previously. The specific estimation function should be used (see above), and it seems to be broken (value was not saved).
Also, it should be possible to fill in "biophony" without specifying the species.

**Comment by LiuDilongNJ** [comment]
We can only fill in the Call Distance after we have clicked on the Estimate call distance button. If we need to modify it, we need to click on the Estimate call distance button again. In other words. The Call Distance is not allowed to be filled in on either the tag creation or the tag edition pages. If so, can we remove the checkbox of Distance not estimable?

**Comment by kdarras** [comment]
correct. But the value should be displayed in the tad edition window

**Comment by kdarras** [comment]
2 issues:
-please allow users to select no sound type (add a blank menu entry)
-re-enable the "distance not estimable" checkbox. Users creating tags for bats, for instance, need to be able to check that box from the start (bat distances are always not estimable).
![Screenshot from 2022-12-16 13-32-32](https://user-images.githubusercontent.com/7696198/208100372-44c14efd-05ff-4671-a377-c33173c02c4c.png)

**Comment by kdarras** [comment]
a few issues:
-as you see in this screenshot:
![image](https://user-images.githubusercontent.com/7696198/209107620-8536391b-c02a-4725-a9bb-4a4a21a8c3ef.png)
The species is not displayed for the "phony-only" tags. Indeed I forgot to mention the point that if there is no species, we should display the sound type, and if there is no sound type, we should display the phony. Up to you whether you want to implement it or I should create a new issue
-the phony field is currently not editable. It should be editable, however. In the case of biophony tags, changing the phony to another type should clear the other fields (show a warning? up to you).
![image](https://user-images.githubusercontent.com/7696198/209108407-61564fff-67ea-4897-8eda-2765aa762251.png)
-the distance estimation function is still broken. After saving the value and opening the tag editing window, no value was saved.

**Comment by kdarras** [comment]
2 issues remaining:
-the orange shading of tags should only apply to biophony tags (since this is where distances can be defined)
-the species box should not be filled in automatically after opening the tag edit window of a tag where no species was filled-in, but a species was entered upon first creation. To reproduce: 1) create a biophony tag and select a species. 2) delete the species, save the tag (this works) 3) edit the tag. You will see that the species reappears in the box, although we just successfully saved a tag with an empty species field. It also makes me think that the removal of the species should be shown explicitly with "nothing selected", just like you did with the sound type

**Comment by LiuDilongNJ** [comment]
I will modify it directly. Also, regarding the issue below, I'd like to know, if I click on the checkbox again, should it revert to the distance saved before? Or is it still blank?

**Comment by kdarras** [comment]
Clicking the "distance not estimable" checkbox should remove the distance value, if there is one. If we click the checkbox again before saving the tag, then yes, ideally, the previously filled-in distance should be filled in again (but this is a bonus :)

**Comment by kdarras** [comment]
Working in Docker as desired now.
(but note: the first time only, clicking the stop button after playing back the file to estimate the call distance led to "error undefined" and logged me out)
