### ISSUE TITLE
center world map

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#270]
The most common display convention is to have Africa in the middle of the world map to show the half of the globe where most continents are. It means the current view, that seems centered on the West Pacific, needs to be adjusted:
![Screenshot from 2022-11-02 11-31-04](https://user-images.githubusercontent.com/7696198/199468351-1ba4df64-1a63-4940-8b2e-0e57a57a2529.png)

**Comment by kdarras** [comment]
yes the default in most regions of the world is to center world maps like that:
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/ef1b3b65-5c22-4b1d-bde5-989d673e3629)

It could be a political issue, but it's simply centered on 0 degrees latitude and 0 degrees longitude :) It's a convention. However, it also makes sense because it emphasizes the view where most continents are in focus, because the symmetrically opposed point on the globe is in the ocean, and this other half of the globe is mostly water.

**Comment by kdarras** [comment]
Note: could markers be replicated across adjacent world views like on https://explore.dawn-chorus.org/?lang=en ?

**Comment by LiuDilongNJ** [comment]
Got it!

**Comment by kdarras** [comment]
Works in Docker, will confirm once online
