### ISSUE TITLE
displaying IUCN GET on maps

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#271]
For the maps we should display:

- markers in different colors for each realm
- realm, biome, and functional group info inside a hierarchical map legend with checkboxes allowing to show and hide the respective ecosystems. Only the currently visible ecosystems should be in the legend.

**Comment by kdarras** [comment]
Note: accordingly, different counts in clusters should not be represented with color anymore, but maybe with circles that have numbers inside?

**Comment by LiuDilongNJ** [comment]
Is this for the project page or the collection page or both. The project page already has the ability to filter the collection, do they have to exist at the same time?

**Comment by kdarras** [comment]
For all maps, on the project and collection pages. Indeed project pages should have the possibility to filter collections and to filter ecosystems, in two different menus.

**Comment by kdarras** [comment]
Unchecking the Leaflet filter box for the single and only realm/biome/functional type that was used in this collection crashed the collection page:
![image](https://github.com/user-attachments/assets/6ab41f29-e796-4661-a1d3-1547f51b63f1)
Exiting the full screen view also crashed the page in the same way.

Excellent mixed cluster implementation!
![image](https://github.com/user-attachments/assets/7b4a3c56-c235-4e50-bcc7-2e865ad5e359)

**Comment by kdarras** [comment]
Excellent.
Working in Docker
Will test on WWSS project once online.

**Comment by kdarras** [comment]
Cannot test. Worldwide Soundscapes project unaccessible:
![image](https://github.com/user-attachments/assets/a385e9e3-2f65-4df6-8b35-5b40c90acefa)
https://ecosound-web.de/ecosound_web/collection/index/106

**Comment by kdarras** [comment]
Testing on another collection, it seems not to work properly (or I haven't found my mistake):
https://ecosound-web.de/ecosound_web/collection/show/3
This collection contains 12 sites with filled-in coordinate and ecosystem info. However, only 2 sites appear.

**Comment by kdarras** [comment]
The previous problem was solved.
However, there is a new one that I am guessing this may be related with the new feature. After logout, I get this error message. Only a reload can remove it (pressing OK does not suffice):
![image](https://github.com/user-attachments/assets/a00073f7-256c-4b12-bc1f-310eeb69c5f1)

**Comment by kdarras** [comment]
working online

**Comment by kdarras** [comment]
completed in #511
