### ISSUE TITLE
assigning sites to multiple projects and collections

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#272]
we need to break out the project_id-site_id information from the site table and put into a linkage table to assign sites to different projects and collections:

- site_id
- project_id
- collection_id

or maybe:
- site_id
- parent_id
- parent_type (project or collection)

The maps shown at the project level should continue showing all the sites assigned to the project. The input of the collection_id is optional: It must be possible to assign sites to entire projects without specifying the collection.

The map should include the collections in the legend with checkboxes so that people can zoom into the sites that belong to particular collections.

The sites tab in the admin interface should have a two-stage drop-down menu to filter the sites by project (required) and collection (optional filter).

The assignment of sites to projects and collections happens with a new button inside the site table in the admin interface, where sites can be assigned to projects and the collections within, similarly to the user privileges window.

Similar to https://github.com/ecomontec/ecoSound-web/issues/44

**Comment by LiuDilongNJ** [comment]
I think we can still achieve this effect even if not creating a new table. It's a bit complicated to correspond to both project_id and collection_id. In fact, it only needs to correspond to collection_id.

**Comment by kdarras** [comment]
Good point, sure - we can get the project id from the collection id

**Comment by LiuDilongNJ** [comment]
1、Administrators and project managers can use this button to assign sites. other users can not assign.
2、Administrators can assign sites to all projects, and project managers can only assign sites to projects they own.

**Comment by kdarras** [comment]
1. yes
2. yes

**Comment by LiuDilongNJ** [comment]
1,3,4 is ok,
For 2, because the multi-to-multi relationships of site and collection are in conflict with the map aggregation function, it is difficult to implement checkboxes and errors in the number of coordinates may occur.

**Comment by kdarras** [comment]
Alright I see, thanks

**Comment by kdarras** [comment]
saving site to project without specifying colleciton does not work:
![image](https://user-images.githubusercontent.com/7696198/208095326-fd13a6ca-f743-483b-a963-bc142af031d4.png)

**Comment by kdarras** [comment]
the sites specific for a different collection than the currently selected collection, but belonging to the same project, erroneously appear under the site selection drop-down when uploading a recording:
![image](https://user-images.githubusercontent.com/7696198/208096956-aebdbbf6-b8c1-4b12-bd21-99ff6f5a4b94.png)
![image](https://user-images.githubusercontent.com/7696198/208096994-b9f419f1-fbde-4593-8ca7-3d8489811c07.png)

**Comment by kdarras** [comment]
we should use the same icon as the one we are using for setting user privileges to assign sites to collections, not the icon that we use for editing passwords like now:
![image](https://user-images.githubusercontent.com/7696198/209093694-87f30603-db9d-4cdc-9d12-48080419c064.png)

**Comment by kdarras** [comment]
working in Docker otherwise

**Comment by kdarras** [comment]
Thanks for replacing the icon. I forgot to mention that the recordings tab also needs a project drop-down menu... created #301

**Comment by kdarras** [comment]
would it be possible to display a grayed out checkbox next to the checkbox when only some of the collections of the project are checked?

**Comment by kdarras** [comment]
Excellent! Just use the same consistent symbology everywhere.
