### ISSUE TITLE
improving projects documentation with short and rich-text description

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#274]
Currently, the project description is a RTF field that is shown on the project overview page.
We need a new field called description_short (no RTF formatting) which can be displayed instead of the RTF description on the projects page.
The RTF description field can be shown on the corresponding project page, before the map.

The map should get a title: "Map of project sites"
The map shown for the corresponding collections should be called "Map of recording sites"

**Comment by kdarras** [comment]
Looks good, however:
![image](https://user-images.githubusercontent.com/7696198/217219206-f4cb35c6-8563-4446-a24a-508dd363fdca.png)
The short description needs to appear on top of this window, and we need to have a consistent style, so: we do not need RTF formatting for that one. Currently, it is inverted. Actually: we need the short description on the public overview of projects, and the long description on the respective project page.

**Comment by LiuDilongNJ** [comment]
Fixed

**Comment by kdarras** [comment]
works in Docker
