### ISSUE TITLE
public tags

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#284]
we need to be able to make tags publicly visible and manage this via the collections tab in the admin interface with a new checkbox column in the table. The old "public" field could be renamed "public_access" and the new field could be called "public_tags"

**Comment by LiuDilongNJ** [comment]
1. Users without permission can only view the tag, but can not edit.
2. Can not see the tag information in the management page.
Is that right?

**Comment by kdarras** [comment]
correct! View-only tag access for visitors. Admin interface access only for (registered) users.

**Comment by kdarras** [comment]
doesn't seem to work yet:
![image](https://user-images.githubusercontent.com/7696198/217224655-913e6dfa-5590-4041-890e-b44fa3359873.png)
![Screenshot from 2023-02-07 11-49-29](https://user-images.githubusercontent.com/7696198/217224914-d1e5f5c2-3e95-4123-8a60-07a3d5238327.png)
tags are not visible publicly (checkbox is checked)

**Comment by kdarras** [comment]
this works well and is well-implemented, however, please hide the identity (user name) of the tag creator and tag reviewer.

**Comment by kdarras** [comment]
Well done.
However, the "next tag" button does not work when not logged in: the page goes to the next tag, but the next tag window disappears.

**Comment by LiuDilongNJ** [comment]
I have fixed it, please test it again.

**Comment by kdarras** [comment]
Working in Docker
