### ISSUE TITLE
mobile-friendly homepage

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#290]
Currently, it is not possible to see the login screen on mobile devices, and the image on the home page does not resize automatically:
![image](https://user-images.githubusercontent.com/7696198/204372713-9670cec7-996b-4889-a28d-9b4b3323e0bb.png)
Note that this also applies to the website running on a desktop computer, below a threshold window width of approximately 900 px.
All other pages should be checked too regarding picture, spectrogram and map resolutions, and should smoothly transition from landscape- to portrait orientation designs on phones.
If handling is too difficult on phones or the resolution is too low, consider removing analysis functions such as tagging, tensorflow models, acoustic indices and informing the user with a message banner such as "Analysis functions only available with computer and tablet screens".
Correspondingly, tablets should work fine with the website too.

Related to #385

**Comment by bwentzloff** [comment]
I have a PR [here](https://github.com/ecomontec/ecoSound-web/pull/291) that should fix the login link and logo on the homepage.

**Comment by kdarras** [comment]
I reproduced both problems in the browser by resizing the browser, and simulated their resolution with the code fix.
Unfortunately, the new code duplicates the login link:
![image](https://user-images.githubusercontent.com/7696198/205068306-baf8e988-7eaa-4b4d-ad2e-218381982590.png)
