### ISSUE TITLE
adapt color of GADM and GET fields in site creation mask

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#302]
Currently, the GADM and GET fields in the site creation mask are white when inactive (i.e., empty) and grey when filled. This is counter-intuitive and non-standard. They should be grey when it is not possible to fill them, and white when filled (or empty and possible to fill, actually).
Note that this behavior is correctly implemented in the sites admin table, but not in the sites creation mask:
![image](https://user-images.githubusercontent.com/7696198/210214826-2d1c6515-6823-47f0-a91b-17dc78fe126f.png)

**Comment by LiuDilongNJ** [comment]
Can you tell me which browser you are using?

**Comment by kdarras** [comment]
Firefox

**Comment by kdarras** [comment]
works in Docker
