### ISSUE TITLE
speed up loading of projects with many sites

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#313]
Taking the example of the Worldwide Soundscapes project with >6K sites, we need a solution for avoiding too long loading times.
Some alternatives off the top of my head:

- load data of first collection by default, and load other collections only after clicking the corresponding radio button (might require another button to execute the query). Would this make checkboxes (for multiple collection selection) possible? We would still need to keep the "all collections" option, but users will understand why it takes along time to load if the sites number is indicated in parentheses next to it.
- All actions (such as paging, searching and ordering) are handed off to a server where an SQL engine can perform these actions on the large data set . As such, each draw of the table will result in a new Ajax request to get the required data.

**Comment by kdarras** [comment]
any thoughts on this @LiuDilongNJ ?

**Comment by LiuDilongNJ** [comment]
All actions performs (such as paging, searching and ordering) are handed off to a server where an SQL engine can perform these actions on the large data set . As such, each draw of the table will result in a new Ajax request to get the required data.

**Comment by kdarras** [comment]
Alright, just like myphpadmin I suppose? I imagine such refactoring would be needed for many parts of the website where we will hit the limits of loading the entire dataset.

**Comment by kdarras** [comment]
could you explain which aspects of the website this change would affect? Would it similarly affect the loading of tables within the admin interface?
