### ISSUE TITLE
Original file names in tag exports

### ISSUE THREAD

**Issue by arnolderich** [ecomontec/ecoSound-web#316]
The exported csv file does not indicate the original file name, but only lists the names as displayed by ecosound. This behavior make it difficult to relate tags to their specific sites (given in original file name) in case of anonymised ecosound names.

**Comment by kdarras** [comment]
I think it would be even better to have the primary key (the unique sound_id) inside the exported tag table. This way, you can join it with the exported recordings data table.

**Comment by kdarras** [comment]
related to #7 , added to next version development plan, @LiuDilongNJ
