### ISSUE TITLE
implementing batdetect2

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#334]
We are currently testing [different bat classifiers](https://docs.google.com/spreadsheets/d/1j-pY1730a5rGcLn0fLcOcTAgFnznflqjrEYCH-M0RyQ/edit#gid=0) and it is likely that we will choose to implement [batdetect2](https://github.com/macaodha/batdetect2) on ecoSound-web, similarly to how BirdNET was implemented:

- dependencies should be installed
- batdetect2 should be integrated into the models table, which should be expanded to make future model addition as sustainable (easily expandable and adaptable) as possible (details to discuss)
- batdetect2 should be chosen from the drop-down menu that appears when clicking on "Tensorflow models", which should be renamed to "Classifiers", and the documentation icon should link to the GitHub repository
- the parameters specific to batdetect2 should appear in the window, and left at their default values if nothing is entered
- the results should be saved as new tags, and non-matched species names should be inserted inside the comment

**Comment by kdarras** [comment]
Batdetect2 runs suspiciously fast but outputs no tags with local test files for which I usually got lots of detections.

Input of confidence thresholds between 0 and 1 (this is the original range accepted by batdetect2) should be allowed instead of 0.1 to 1.

For instance, this recording:
https://ecosound-web.de/ecosound_web/recording/show/523954
has 24 tags inside, all generated with batdetect2 (all other recordings contain tags that were generated offline with batdetect2 and may be used for testing purposes).

**Comment by LiuDilongNJ** [comment]
BatDetect2 doesn't detect the ogg files in the path, which I have modified and successfully generated tags. Also, I tested with some low frequency non-bat audio and it also generated tags, and the detected frequencies exceeded the maximum frequency of the audio file itself. I'm wondering if there needs to be a limit to how many frequencies above which BatDetect2 can be run.
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/9395f390-4018-493f-8878-ed61fb006718)

**Comment by LiuDilongNJ** [comment]
BatDetect2 didn't detect the ogg file in the path, I've modified it and generated the label successfully.

**Comment by kdarras** [comment]
it should run on the WAV file

**Comment by kdarras** [comment]
I converted one of the FLAC files to a WAV and added it to the same collection to run batdetect2 on it. Now it works, even with these large files!

batdetect2 should run on the WAV file only. It won't work with any other audio format.

**Comment by LiuDilongNJ** [comment]
It works with all formats of audio, I've finished it but haven't uploaded it yet, I'm fixing other problems.

**Comment by kdarras** [comment]
Works in Docker.
However, there is no feedback to the user after executing a model from the admin interface. Please add a popup message "Model running on [recording name] in background" (same style as when we upload recordings), since you have already implemented this :)
