### ISSUE TITLE
multiple rows editing in admin interface

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#342]
Add a new column for managing the table entries in the admin interface, containing checkboxes in each row like this:
![image](https://user-images.githubusercontent.com/7696198/227511486-598927cd-4d1f-4437-b2b9-69c91109986a.png)

The checkbox above the table should cycle between: select all rows in current page / select all rows in entire table / select no row.
The selection should operate on the currently filtered rows only, and text should show up next to the checkbox when more than the currently visible rows are selected: "selected all (filtered) rows across all pages"

In this way, multiple rows can be selected to do the following:
- for all tables except projects and collections: deletion (including acoustic indices and users - if this is a good practice)
- for projects (add), collections, recordings, and tags: viewing/opening
- for site and user tables: edit privileges/assigments
- for recordings: run models (but this probably requires #125 ?)

The corresponding icons should appear above the table after selecting something and should not be shown inside the table rows anymore.

**Comment by LiuDilongNJ** [comment]
Normally, the buttons for each row should not disappear after the data is selected, this button is only valid for this row, both buttons will exist at the same time.

**Comment by kdarras** [comment]
I think it is more elegant to have the action buttons displayed only above the table. This way, there is less redundancy and they are more visible because the individual row buttons are often at the end of the rows and we need to scroll.

It is probably better that the buttons stay visible above the table (but grayed out - inactive) and become active when a row is selected, so that the users are aware of the possible actions.

**Comment by LiuDilongNJ** [comment]
Cool, so we only keep the button to change the user password in the table.

**Comment by kdarras** [comment]
ah yes, true! I don't think we will batch-assign passwords to users :)
Or do you think that this particular button could be grayed out again if more than one row is selected?

**Comment by LiuDilongNJ** [comment]
I'll make it gray again.

**Comment by LiuDilongNJ** [comment]
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/1bfb8d5b-371f-4991-bd00-3ab0bef44356)
Can we remove the ability to select all users? And add paging. We can select ALL and select all to operate on all users.

**Comment by kdarras** [comment]
Good ideas, agreed!

**Comment by LiuDilongNJ** [comment]
If you delete a user, do you need to delete all the projects, collections, recordings, sites, tags, indexlogs created by that user. I suggest to use active function, or we can implement a soft delete function so that it will not be shown in the user list.

**Comment by kdarras** [comment]
You are right, for users there should be no delete button at the moment. Later, users should have the right to delete their account and personal data but we need to think about what this implies. For the moment, the batch editing should only use the existing functions.

**Comment by kdarras** [comment]
The feature works well. However, please use a white background for the drop-down menu (same aestehetics as other drop-downs) to select the number of entries, and move the buttons below the search bar. Maybe also align the text of the entries drop-down with the "Project" drop-down label if it looks better. Finally, write "all" instead of "All"

**Comment by kdarras** [comment]
Since we will implement batch-processing of recordings later, simply inactivate the "models" button when multiple recordings are selected. Note that however, executing it on single recordings doesn't currently work.
