### ISSUE TITLE
Species excluded from BirdNET execution

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#358]
When running BirdNET Analyzer V2.2 on this recording: https://ecosound-web.de/ecosound_web/recording/show/515469#
The "Oriolus oriolus" bird species tags are not inserted into the recording. However, when analysing that same recording with BirdNET Analyer V2.2 offline, 8 more detections of this species are found in the results pasted below:

Start (s) | End (s) | Scientific name | Common name | Confidence
-- | -- | -- | -- | --
48 | 51 | Fringilla coelebs | Common Chaffinch | 0.6044
138 | 141 | Oriolus oriolus | Eurasian Golden Oriole | 0.5742
144 | 147 | Oriolus oriolus | Eurasian Golden Oriole | 0.7073
153 | 156 | Anser anser | Graylag Goose | 0.8855
156 | 159 | Anser anser | Graylag Goose | 0.5822
162 | 165 | Anser anser | Graylag Goose | 0.5985
165 | 168 | Anser anser | Graylag Goose | 0.5755
198 | 201 | Cyanistes caeruleus | Eurasian Blue Tit | 0.5969
201 | 204 | Cyanistes caeruleus | Eurasian Blue Tit | 0.5548
261 | 264 | Poecile palustris | Marsh Tit | 0.5362
300 | 303 | Coccothraustes coccothraustes | Hawfinch | 0.7746
345 | 348 | Fringilla coelebs | Common Chaffinch | 0.5169
420 | 423 | Oriolus oriolus | Eurasian Golden Oriole | 0.6617
423 | 426 | Oriolus oriolus | Eurasian Golden Oriole | 0.8278
432 | 435 | Oriolus oriolus | Eurasian Golden Oriole | 0.8833
462 | 465 | Oriolus oriolus | Eurasian Golden Oriole | 0.9132
498 | 501 | Oriolus oriolus | Eurasian Golden Oriole | 0.618
501 | 504 | Oriolus oriolus | Eurasian Golden Oriole | 0.8496

**Comment by kdarras** [comment]
I also found that this detection is found with BirdNET analyzer v2.2:
135 | 138 | Phylloscopus sibilatrix | Wood Warbler | 0.1382

but not inserted into the corresponding recording: https://ecosound-web.de/ecosound_web/recording/show/516793#

**Comment by LiuDilongNJ** [comment]
https://ecosound-web.de/ecosound_web/recording/show/515469# This recording is no longer accessible

**Comment by kdarras** [comment]
You are right; these recordings have been removed: maybe you can check recordings in this project: https://ecosound-web.de/ecosound_web/collection/index/111 (except collections "batdetect2 validation" and "Biosphere reserve Oberlausitz" and "Orthoptera validation")
The recordings in these collections contain detections generated by BirdNET v2.2 offline, which were then integrated into ecoSound-web manually as taqgs. So if you run BirdNET from ecoSound-web on these recordings, you should see where the differences arise. I think it is linked to the species ID, which points to a potential problem with the names matching?

**Comment by LiuDilongNJ** [comment]
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/e5b8bbe9-8715-4112-b660-727c1d0a9846)
The results are taken from the code on github, theoretically the results should be the same and all the results will generate tags, if our species list doesn't contain this species it will also be recorded in the comments column. I would like to know if the offline version you are using is the GUI version? Are the runtime parameters exactly the same or is it modeled for further learning. Also, I observed that there was an update in v2.2, and I wonder if this has any effect on the results. I've used two test methods so far. The results seem to be consistent.

**Comment by LiuDilongNJ** [comment]
Can you help me find a similar problem? I'll find out what the problem is.

**Comment by kdarras** [comment]
The offline version we used was 2.2, with the same settings. Yes, the versions after that give different detection results. At the moment I cannot help with testing, I am switching computers and have no root access here at the moment... But I agree it is difficult to reproduce... so we could make this a won't fix issue?
What about developing the message that reports the number of inserted tags? We could write: "[BirdNET vx.x/batdetect2] found X detections. Y tags were inserted (Z tags with unmatched species: names inserted into comments)". If X=/=Y, then we could show a warning "Number of detections does not match number of inserted tags. Tag insertion aborted. Contact administrator."

**Comment by LiuDilongNJ** [comment]
Good idea.

**Comment by kdarras** [comment]
works in Docker
