### ISSUE TITLE
review data table in admin interface

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#363]
We need to be able to access, edit and download the review data from the admin interface, with the same features as the other tables:

- project/collection drop-down filters
- export reviews button
- editing only for the review creators, project managers or admins

**Comment by LiuDilongNJ** [comment]
Comments can't be edited on the tag page, what fields can be edited on the admin page?

**Comment by kdarras** [comment]
All fields need to be shown according to #7 , but only tag_review_status, species_id and note need to be editable

**Comment by LiuDilongNJ** [comment]
我对这个功能有一些想法:
1.tag review页面像图片所展示的,我们无法区分一个review属于哪一个标签,除非我们加上tag的信息.为此,我给出两个解决方案
(1)在tag review页面追加tag信息,例如时间和频率;
(2)去除tag review页面,将tag review信息追加到tag页面.以review列显示该tag的所有reviews,并增加一个编辑评论的按键;
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/928b1ba4-5b7e-42d2-9fe2-49a75808ad04)

**Comment by LiuDilongNJ** [comment]
2.Whether there is a need to add a recording filter to the tag and tag review pages. I don't think we usually need to look at two different recording tags at the same time. If added. It will no longer show all the tags under the collection, but only the tags under a particular recording. Also, we need to add a search function to the filter.
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/179fb114-885a-45af-8e42-6ed7307bb3c4)

**Comment by kdarras** [comment]
Hi Dilong, I think the first comment is still in Chinese :)
Regarding 2.: yes indeed this is planned (#388 ) so welcome to implement

**Comment by LiuDilongNJ** [comment]
Sorry, I edited my comment above.

**Comment by kdarras** [comment]
What we decided to implement works in Docker.

However, I may have taken the wrong decision, as embedding the reviews into the tags table creates two problems:
- the user experience, that was based on accessing single tables' data in each tab separately, is inconsistent now, and users may not find the reviews data easily as a result
- it is not possible to batch-edit reviews because we can only select single reviews (or maybe also multiple reviews for a single tag, but I haven't checked)

Therefore, I suggest that we revert to the classical, less elegant solution of having a new, dedicated tab for tag reviews.

Important note: it seems that multiple reviews for one user are not allowed anymore, which is nicely implemented as review buttons are grayed out when a user has already given one review. However, for my admin account, this error message appears when I try to add another review:
![Screenshot from 2023-11-15 17-23-23](https://github.com/ecomontec/ecoSound-web/assets/7696198/55200cfb-6493-45be-96aa-f49112ee8652)

Let me know whether we can address these issues or need to create new ones, as I am well aware that this may be beyond the original plan/decision.

**Comment by LiuDilongNJ** [comment]
I've optimized the commenting issue, after commenting the tag page will be refreshed and the user will not be able to comment after commenting, now it seems to be more reasonable. Regarding the review, I will make a separate page, but do I need to keep the ability to expand the review in the current tag page?

**Comment by kdarras** [comment]
no need to expand tag entries (under the tags tab) to view the reviews data anymore.

**Comment by kdarras** [comment]
Works in Docker
