### ISSUE TITLE
multiple acoustic indices for multiple recordings

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#367]
Project managers (who are able to access the recordings table from the admin interface) need to be able to compute alpha acoustic indices of multiple recordings from the admin table.

Multiple indices should be selectable with checkboxes instead of the current drop-down that appears from the player.

However, the window that appears should show the confirmation that it will run on X recordings (as per #125) and the button to launch the job should be called "Compute and save to log" (because we won't show the output of multiple recordings and we will save it to the log by default).
Similarly, the button for single recordings should be called "compute" instead of "submit".

Requires #125 to manage the processing jobs queue.

**Comment by LiuDilongNJ** [comment]
1.Can a user select more than one recording to perform an index function on the admin page?
2.What information about the recording is displayed on the left side of the page?

**Comment by kdarras** [comment]
Since this is based on #125:

1. the function would allow the analysis of multiple recordings
2. we would show the information related to the items added to the queue, their status and progress, the time elapsed

I edited the first post for clarity

**Comment by kdarras** [comment]
done with #125

**Comment by kdarras** [comment]
working in Docker

**Comment by kdarras** [comment]
By the way, I noticed that now, when launching the acoustic index button from the spectrogram player, the hover-on info of the tag gets displayed in the lower left corner:
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/98b0e391-4d91-4c4b-8122-4506745fd695)

**Comment by LiuDilongNJ** [comment]
How to operate can encounter such a situation, when we click on the tag appears after the tag information, if the mouse away from the tag range, it will automatically disappear.

**Comment by kdarras** [comment]
This is a new issue: #437 . the tag info now pops up every time I create a tag.

Otherwise, the new feature works in Docker

**Comment by kdarras** [comment]
It seems that the acoustic index computation is limited to 1000 items? When I launched a job for two indices on 559 recordings, the total shown in the queue was 1000, and when I launched another one for 2 indices on 3779 recordings, it was again 1000:
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/6f3ace9a-e63f-4671-ae0d-ba830c9bcf0e)

**Comment by kdarras** [comment]
+ one more small issue:
after deleting one index row from the index Logs tab, the table did not display any result anymore:
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/449e0f23-7b2a-4bf5-bf54-214317ad4321)
they re-appeared after a page refresh

**Comment by kdarras** [comment]
working in Docker
