### ISSUE TITLE
Downsampling WAV at upload

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#375]
Under a new "pre-processing" step before the upload mask, add a checkbox next to "resample recordings", which activates a drop-down box allowing the following sampling frequencies:
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/6f4e639e-7968-4c46-b2b3-9f57de52d65f)
as well as a custom frequency to be entered by the user.

Add an info or warning icon that upon mouseover displays: "Only the resampled recording will be kept on server. Back up your original files."

Keep in mind that this needs to be implemented modularly, as further SoX features may be implemented soon (#350 ), and SoX is long in the tooth so that it may be replaced one day. Consider that scikit-maad may also be used, and that we are unclear about the use of WebAudio.

Also note that the meta-data of the original files must be faithfully transferred to the new files (#424 ).

Transferred to issue #502 : Allow downsampling of WAV recordings before upload.

**Comment by kdarras** [comment]
what tool would you use for resampling @LiuDilongNJ (WebAudio, SoX, scikit-maad)?

**Comment by zdroyer** [comment]
Can be merged with #389

**Comment by kdarras** [comment]
Adjusting this issue instead of merging (as it is part of another package) to facilitate the future #389

**Comment by kdarras** [comment]
Adjustments needed:
Use "continue" instead of "submit" here:
![image](https://github.com/user-attachments/assets/d08eb0db-441f-4f6a-979d-4e8d3d7e26c1)

**Comment by LiuDilongNJ** [comment]
This feature is only for wav files, right?

**Comment by kdarras** [comment]
True. Sorry for the confusion. Will re-test after taking your updated code which will allow me to check the uploaded WAV files.
Then we need to adjust the window shown above with "resample recordings (WAV only)"

**Comment by kdarras** [comment]
Working in Docker, minor adjustments mentioned above pending

**Comment by kdarras** [comment]
Working in Docker.
Please remove the tick mark from the "continue" button as it implies that this process will be over (or use another icon).

**Comment by kdarras** [comment]
working online

**Comment by LiuDilongNJ** [comment]
The resampling function is performed on the server, the user needs to upload the original file to the server, then the server generates the resampled file and deletes the original file. If set on the client side, some browsers or lower versions of browsers will not be able to use the resampling function, because only the Web Audio API is supported.

**Comment by kdarras** [comment]
completed in #511
