### ISSUE TITLE
continuous playback rearrangement

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#382]
Move the continuous playback option into the playback options menu (similar design to #378 ) since this is related. Use an icon with a horizontal arrow passing through a vertical line and give info on mouse hover: "continue playback beyond current frame"

**Comment by kdarras** [comment]
When reaching the end of the spectrogram and while loading the next view, there is a short error message "error undefined" appearing now.
Also, the frequency filter setting is lost when using continuous playback on a frequency-zoomed selection.

To clarify the request above, what I meant was that the continuous playback options menu could be the playback button with an expandable/collapsible sub-menu where the continuous playback option can be moved. Something like this but less ugly:
![image](https://github.com/user-attachments/assets/4d3ef602-55df-45c7-8118-8ef086bc91ab)

Later, we will move the playback speed slider inside as well so that all playback options are grouped in/under the playback button (#285 ).

**Comment by LiuDilongNJ** [comment]
I used the method of displaying the drop-down bar when the mouse is hovering. In addition, I fixed a problem that the time and image would be wrong when playing automatically. Regarding the filter button, it seemed to be like this before, and I don’t know what its function is.

**Comment by kdarras** [comment]
Thanks for fixing this bug Dilong! It probably is #431 and #295.

I created a new issue (#495) to keep the frequency filter (it filters out the frequencies above and below the spectrogram extent when enabled) state between frames.

However, the continuous playback button should stay as it was before: a toggling button (green active/grey inactive) which does not start playback. The point is that users may want to enable or disable continuous playback while playback is happening, without interruption. The icon design also does not intuitively suggest that it will start playback.

I prefer not to show all the playback options every time the mouse hovers on the playback button, as most users will not use the options, so it is better for them to click something (an arrow or plus sign) to display the options.

Note that there are two bugs but I am unsure when they appeared:
- making invalid selections in a particular way crash the page when zooming:
[Screencast from 2024-08-15 16-21-39.webm](https://github.com/user-attachments/assets/d725b7b0-51e3-4909-83b4-39914f0602fc)

- Each time the spectrogram is reloaded, there is an "Error undefined". This also happens on the live web server after editing tags: 
[Screencast from 2024-08-15 16-15-18.webm](https://github.com/user-attachments/assets/5d947679-4a4e-4370-a65e-ee5da656e0e1)

For both of these, let me know whether I should file new issues.

**Comment by kdarras** [comment]
working in Docker
Can the arrow be closer to the playback window and smaller? Maybe a plus sign would be more intuitive after all... because the arrow is big and looks like a rotated playback icon.

Should I create new issues for the two bugs I mentioned @LiuDilongNJ ?

**Comment by LiuDilongNJ** [comment]
I tried reducing its size and distance.
Can you show the operation in more detail? I tried it several times and it didn't work, maybe I missed some steps. You can create two new issues.

**Comment by kdarras** [comment]
Thanks Dilong

To reproduce first issue: make a selection in the lower right corner. Then, extend its upper border or upper left corner with your mouse. You will see that the frequency text box shows indefinitely increasing frequency values that are impossible. Zooming then results sometimes in a crash, sometimes not.

To reproduce the second issue: Take a recording, zoom into it, enable continuous playback, play back, wait until it reaches the end of the frame. When it loads the next frame "error undefined" will be shown.
[Screencast from 2024-08-16 15-09-55.webm](https://github.com/user-attachments/assets/83c21010-ec18-450a-8a50-7cbad0c4f9e0)
Note that when I tried it on another recording, zooming crashed under simpler conditions (any zoom into a portion that contains the bottom of the spectrogram crashes):
[Screencast from 2024-08-16 15-08-11.webm](https://github.com/user-attachments/assets/40f7e274-e5bc-409f-972e-83ef6c8093f8)

This is related to #465 and happens on the live server too. It happens every time you save an edited tag. I am just not sure when it appeared. Just tell me your decision.

**Comment by LiuDilongNJ** [comment]
I have been testing for a long time. I can reproduce these two problems skillfully.
The first one is normal when using Google Chrome. When using Firefox and Edge browsers, when the window is maximized, there will be no such problem. When the window is not full screen, there is a bug.
The second one is that when using Google and Edge browsers, everything is normal, when using Firefox browser, there is an error message.
You can also test it a few more times to see if the situation is consistent with mine.
I did not change this part of the code. So please recreate two problems.

**Comment by kdarras** [comment]
working online

**Comment by kdarras** [comment]
completed in #511
