### ISSUE TITLE
Project and collection page redesign and map improvements

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#386]
On project and collection pages: Make maps narrower and less high and add dynamic site/recording/users/tags statistics next to them (in a box? whatever looks nice).

Add a button to maximize maps for people who want to take a better look. Sync map extent with collections in project page: if all sites of a collection are not within the extent, the collection should be filtered out, and the collection count should reflect this (same as for recordings count in collection page).

**Comment by kdarras** [comment]
@LiuDilongNJ 's suggestion: "It can be designed to when you open the collection page, the introduction is displayed on a full page. When you scroll down, the introduction hides, and the map and list are displayed directly."
It would be nice that we only zoom into maps when holding the shift button, or something like this: https://gis.stackexchange.com/questions/111887/leaflet-mouse-wheel-zoom-only-after-click-on-map

**Comment by LiuDilongNJ** [comment]
Is it possible for me to design this page the way I want as I feel it may not be user friendly. I would like to make the interface cleaner and easier to use.

**Comment by kdarras** [comment]
Remove project name to reduce redundancy with the breadcrumb?
![image](https://github.com/user-attachments/assets/cc0c10db-7adc-45f2-bf97-c4aafa89d618)

Then, I tried to open a recording that I just uploaded but got this new error:
![image](https://github.com/user-attachments/assets/7c824194-4991-42e6-91f2-8d7efbbfbe36)

However, I don't have this problem with recordings inserted into the Demo collection of the first Testing project.

**Comment by kdarras** [comment]
working in Docker

**Comment by LiuDilongNJ** [comment]
I'm not sure I understand the last sentence, the recording and the collection both change with the site display of the map.

![image](https://github.com/user-attachments/assets/7cb5a667-5475-4db3-b3da-1c6e5184e589)
![image](https://github.com/user-attachments/assets/c7665fbe-295c-4da9-a748-b216732faea7)

**Comment by LiuDilongNJ** [comment]
Is the full name of the ‘Berbak’ collection ‘Berbak NP phase 1 and 2’?
As you can see from the filter, it has two more coordinates on the left.

**Comment by LiuDilongNJ** [comment]
![image](https://github.com/user-attachments/assets/ce957d95-3d87-4b39-8989-b630ad477547)

**Comment by kdarras** [comment]
OK, so I understand some things better now.

You implemented that the recordings, tags and sites counts in the statistics boxes dynamically reflect what is shown on the map, but by "dynamic", I previously meant that we can show the up-to-date totals there (independently of the current map extent). However, I like this feature, so we can keep it!

I just noticed that the recordings count is not visible anymore either in the collection pages... so you have moved everything into the statistics boxes. Indeed, it makes sense and is elegant. However, we need the totals, so the best solution to solve all problems is to show them inside the statistics boxes, like this:
![image](https://github.com/user-attachments/assets/a4da46dc-14f1-4d29-948d-ff1091b43fad)

Note, however, that we need to specify which users are meant. Please replace "Users" with "Taggers" and only count the users who have tags within the recordings of the current extent.

The problem with the [Berbak collection](https://ecosound-web.de/ecosound_web/collection/show/3) seems to reveal some (access-related?) bugs. When I open it, 12 sites are displayed in the stats boxes (this is correct) but one site on the map. But when I zoom _out_, only one site is shown on the map and in the boxes. So, I don't see what you see.
![image](https://github.com/user-attachments/assets/4da7765f-2673-4001-b71d-9b56ebaf08b3)

**Comment by kdarras** [comment]
All bugs fixed!
working online.

**Comment by kdarras** [comment]
completed in #511
