### ISSUE TITLE
Parse and structure acoustic index results

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#398]
Currently, acoustic index analysis results, when saved, end up in a single column with single or multiple outputs separated by semi-colons where labels are separated with a colon:

We need to restructure the acoustic index table to parse index names and results as to save the numeric values in a dedicated column and the parameters/labels in a separate text column.

Ponder whether we would require a separate run ID key to group multiple results from a single analysis or whether the combination of recording, frequency range, time range already constitutes that key.

Include any other fields that would be required to implement more scikit-maad acoustic feature functions in the future.

**Comment by kdarras** [comment]
I saw that you hard-coded a maximum number of 7 input and 6 output fields. Will this be future-proof or would it better to have a run ID and store the results flexibly in a long format table?

**Comment by LiuDilongNJ** [comment]
How do you want it to be presented on the admin page and in the csv. Then I will modify the database structure.

**Comment by kdarras** [comment]
Please tell me what arguments you see for the wide table format like now versus the long format table (see suggestion above) @LiuDilongNJ so we can settle this.

Otherwise, it seems there is a remaining issue with the naming of fields. Here, the index name is shown inside the "index" column:
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/64c4cf30-09d1-466c-8b76-5dd8df1eb5da)

But is exported under the input_value6 column in the CSV:
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/a863c7b6-3319-45c4-bbe7-68c78f118ee1)

**Comment by LiuDilongNJ** [comment]
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/59556577-249e-49c6-83f4-b0cca2731e94)
This is data from a database, but we need to display it in a visual way in tables and csv's, or you have a better suggestion.

**Comment by kdarras** [comment]
Oh, I think I see the problem now with this implementation: often the number of inputs will not equal the number of outputs, so my proposition will not work.
Either we change my data table structure to something even longer:

- log_id (same ID for same run)
- recording_id
- user_id
- index_id
- minTime
- maxTime
- minFrequency
- maxFrequency
- variable_type (input/output)
- variable_name
- variable_value
- version
- creation_date

Or we keep your proposition with the large, fixed number of columns allowing a maximum of 6-7 inputs and outputs.

Up to you - just let me know.

**Comment by LiuDilongNJ** [comment]
I agree with you.

**Comment by LiuDilongNJ** [comment]
I agree with you.

**Comment by LiuDilongNJ** [comment]
I agree with your idea, you also need to keep the variable_number, so that the query will be faster.

**Comment by kdarras** [comment]
It looks like the new table structure has not been implemented yet- in the latest version that I am testing

**Comment by LiuDilongNJ** [comment]
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/c89615a9-34c5-4801-8184-d24159927714)
![image](https://github.com/ecomontec/ecoSound-web/assets/109188679/7e8c4519-c11c-44b9-abd8-59d0a75a753f)

**Comment by kdarras** [comment]
Looks good - will test with next version (it was still the old structure on the version I installed yesterday)

**Comment by kdarras** [comment]
It looks like inside the CSV and in the admin table, the structure is still in wide format:
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/389570b7-715e-4d6a-a5fa-6f4b59d7c731)
I did a clean re-install.

**Comment by kdarras** [comment]
working in Docker
