### ISSUE TITLE
recording upload reloaded

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#412]
Currently, recording insertion happens in the background and sometimes fails without warning. Since users don't have access to the queue, they won't find their failed uploaded recordings in their collections, which disrupts their workflow.

The new implementation, adapted to the jobs queue (#125) requires:
1. Renaming the "Upload" button to "Add" (use plus sign icon instead of upload icon - just like adding sites). After clicking the "Upload recordings" sub-button, a file browser dialog opens
2. After selecting recordings, a scrollable list of names (with the total number of files displayed below) shows up, replacing the upload widget. Recordings can be added with an "Add more" button. The user can click a "Next" button to proceed or an "abort" button.
3. After clicking "Next", the required parameters should be prompted. These are the usual recording meta-data that were displayed next to the upload widget previously. Then, users can click "insert" to launch the job or "back".

The progress and status of the upload and database insertion can be checked in the new queue tab (#125 ).
The design should account for a soon-to-be-implemented additional signal processing step (e.g., #375 ).

Note: I am unsure whether it would be more practical/esthetic to have popup windows or continue having something like the current implementation where the upload widget smoothly replaces the recordings table. The upload function is peculiar, compared to other batch jobs, as it operates on data that are not yet inside the database.
Note: Later, a sub-button "connect" (link icon) will be added so that users can connect to a server containing online recordings (#218 - implemented separately). Also the meta-data upload function will be enhanced (#418 ), so the file names list should probably be a table (as we may also want to display things like sampling frequency, etc. in the future).

**Comment by LiuDilongNJ** [comment]
After the user uploads the recording, any error in the background audio format conversion, spectrogram generation and a series of other operations will lead to upload failure, this part of the content is relatively large and needs to be reconstructed, so that it is more fluent, and to make the progress of the visualization, in order to let the user know whether they are uploaded successfully or not.

**Comment by kdarras** [comment]
File upload does not seem to work yet:
[Screencast from 13-02-2024 17:59:31.webm](https://github.com/ecomontec/ecoSound-web/assets/7696198/5fc1822f-5982-4963-92c2-b2fe62b80ca9)

Also, the upload mask fields are not reset after my first upload trial (in the video of the second trial you see that I have to enter a date even though "file" is checked)
There seems to be a confirmation message but it is shown too shortly, so I cannot tell whether it was a success or failure message.
Even after several refreshes, the files do not show up in the collection so I cannot test the other features.
I like the clean and simple graphical implementation.

**Comment by kdarras** [comment]
And the queue is quite useful here to show what I tried and the status after 15 minutes :
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/ddd9c4c6-8828-472d-8cd6-9319d476e10c)

**Comment by LiuDilongNJ** [comment]
Please check the contents of the error field in the queue table of the database.

**Comment by kdarras** [comment]
After re-installing from scratch, I still have the same error:
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/ff9382be-2aec-4f97-8042-31f73704d846)
I see no error field. How do I access the "error" field of this table?

**Comment by LiuDilongNJ** [comment]
Please pull the latest branch, I've added the ability for administrators to view queue errors.

**Comment by kdarras** [comment]
Unfortunately no error shows up:
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/e36a6bbd-212c-45c6-8965-eb5510f23e57)

**Comment by LiuDilongNJ** [comment]
I'm sorry for the typos. Please pull up the latest branch and test it again. If you get an error Command failed : soxi -t tmp/XXX/XXX.wav, it could be an error in the byte header of the file, which happened to me.

**Comment by kdarras** [comment]
Upload works now!

Remaining issues:
- starting a second upload creates problems as the meta-data entry mask is messed up and can only be fixed after a full reload (Ctrl-Shift-R)
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/10f312d1-bcdd-4289-8e35-354b26035088)
- the message that comes up after clicking "insert" does not persist long enough to be able to read it. That message should probably read "Recordings are being integrated into the database. Refresh this page periodically." (but I cannot read it - it appears only a tenth or second or so.

Next, I will test the function by uploading a mixed batch of 3000 recordings.

**Comment by LiuDilongNJ** [comment]
Please use your computer to test, my server configuration is too bad. The default number of queues on the test system is one, if you want to open 10 threads at the same time, please run sudo sh run.sh 10 times. When I deploy the server, I will decide how many queues to open according to the server configuration.

**Comment by kdarras** [comment]
Alright, I wanted to upload one batch for all these recordings - so I suppose this needs only one queue.

**Comment by kdarras** [comment]
Selecting 3000 recordings (mostly 1-minute long, 5MB WAV, MP3, or M4A files) gives the user no response after 4-5 minutes: the list of recordings does not show up (yet). When I tried with ~1800 recordings (I am not sure how many exactly I selected), the file list showed up after 2-3 minutes.
Would it be possible to give the user some feedback so he/she knows that something is going on while the user is waiting for the file list to show up?

Also, it would be useful to show this info next to the progress bar: Uploading X recordings + a percentage (or make the bar longer) so that users can see whether upload is progressing or not.

A warning should be shown if the user is uploading files and tries to leave the page before finishing the process by clicking "insert": "Leaving this page will abort the ongoing upload. Abort?"

By the way, can we use horizontal and vertical scrollbars if there is a text overflow?
![image](https://github.com/ecomontec/ecoSound-web/assets/7696198/bed4c81e-c1e3-4ede-bb73-706c0ba177e4)

If a limit needs to be set for recording upload, then the users should be warned with a message such as "Please upload less than X recordings at a time" right after selecting recordings.

I see now how the process could be simpler like you coded it initially, with all steps on one page instead of several pages sequentially!
This way, all fields can be filled in while the upload is progressing, and I suppose that the upload will continue after clicking "Insert", so that users can do something else while the upload progresses - is this correct? In this case, could we please revert to the old layout with all required user input on one page? sorry... :/

One more thing: instead of blocking the database insertion if one recording does not have a datetime string that is in a recognised format, it would be better to proceed with the insertion but to show warning such as: "X recordings had an unrecognised date-time format - used 1970-01-01 00:00:00 instead" and to store the full warning with all filenames inside the error field? I suppose we need an additional "warning" field then...

Also, if some files already exist in the collection, just skip them and show a warning: "X files that already occurred in the collection were skipped" instead of having a failed upload:
![Screenshot from 2024-02-22 09-50-36](https://github.com/ecomontec/ecoSound-web/assets/7696198/1bdbeaf8-2747-4bdb-a14f-e36cab7bbd69)
(By the way, I am not sure how this situation above happened: I uploaded hundreds of files and this displays 26. I do not even think that I clicked "insert" because upload was not finished yet. 26 files were actually successfully uploaded, and 26/0 is not possible)

If the errors and warnings become too long, could be export the table as CSV?

**Comment by kdarras** [comment]
working in Docker
