### ISSUE TITLE
check access to collection/recording before loading sound

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#417]
Currently, the recording is downloaded before the user access rights to it are checked, meaning a slow response of the website only to tell users that they have no access.
User access privileges should be checked before downloading the recordings.
Can be checked when logged out by opening: https://ecosound-web.de/ecosound_web/recording/show/1413

**Comment by kdarras** [comment]
I wanted to test the access to a recording I have no access to when logged out, but browsing to open the corresponding project produced this error:
![image](https://github.com/user-attachments/assets/a745ba41-8d13-4260-9557-d7800ea6a690)

Then, trying to access the recording directly does not work. I tried to open a recording that I just uploaded but got this new error:
![image](https://github.com/user-attachments/assets/7c824194-4991-42e6-91f2-8d7efbbfbe36)

I didn't have this problem with recordings inserted into the Demo collection of the first Testing project at first, but later (maybe after I added meta-recordings to the collection) I could not access them either anymore, with the same template error.

**Comment by LiuDilongNJ** [comment]
There was an invalid code that was forgotten to be deleted, which has been fixed.

**Comment by kdarras** [comment]
Re-installing to finish testing!

**Comment by LiuDilongNJ** [comment]
Sorry, I haven't submitted it yet. After confirming the other issues, I will fix them tonight and submit them together.

**Comment by kdarras** [comment]
Working in Docker. Will test online as loading times will be longer and noticeable.

**Comment by kdarras** [comment]
While testing online, I see I have no access to some recordings with my admin account (kevin):
![image](https://github.com/user-attachments/assets/8dd9d79e-bc68-4689-a74e-5e08613c18ea)

It seeems I have access only to recordings of public collections now.

By the way, as admin all these should be checked grey boxes: 
![image](https://github.com/user-attachments/assets/a9ce3a1c-c8ab-434d-9544-e655e644ea16)
Let me know if I should create a new issue for this latter point.

**Comment by kdarras** [comment]
fixed and working online
Created #503

**Comment by kdarras** [comment]
completed in #511
