### ISSUE TITLE
display ID3, Vorbis, RIFF metadata in recording table

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#424]
We need to display ID3, Vorbis, and RIFF audio metadata tags into the recording table.

***************************************
Obsolete text including mapping functionality:

When files are inserted into a collection, the user needs control over the files' metadata that are used to populate the recording table. We currently already extract the duration, number of channels, and bit rate from the metadata fields of various audio formats and we do not prompt the user for input.

However, users should see what data are extracted and have control over it.

For inspiration and context, popular tools for handling metadata are MP3Tag or the metaflac command-line function of the FLAC package.

Common metadata fields are:
- artist
- title
- album
- comment
- comments
- description

these fields may be lowercase, uppercase, first letter uppercase.

The users need to see the result of the meta-data extraction that maps original meta-data fields to recording table fields. It should allow the user to map the extracted data to other table fields than the default ones and to fill the table fields with other values (NULL or constants). Non-matched fields should be shown too so the user can decide whether to skip them or to direct them elsewhere.
For instance, the comment field may contain gain info that users could insert into the new gain field (#349).

The current form requesting user input for recording date-times, recorder model, microphone, etc. should be superseded by this new form that should additionally allow to choose different sources for these fields, such as:

- the file name (which is only used to extract date-times at the moment)
- metadata fields as described above
- custom constant user input (for instance, a sound name prefix)

Input of required fields should be shown but null values not allowed. For some values, only some sources make sense.

Note: when FLACs are encoded, we copy the original meta-data 1:1 instead of letting users change it  (#389 ).

**Comment by LiuDilongNJ** [comment]
I don't have a good understanding, can you go into more detail? Or draw a simple picture.

**Comment by LiuDilongNJ** [comment]
When uploading, for files that reach 100%, the filename,filesize,md5_hash,sampling_rate,bitrate,channel_num,duration information is displayed and then they are displayed in a table.
How do I then populate the other fields? It doesn't look like any of the other fields, except filename, are automatically extracting useful data. For example, if the filename has "F6" and "zoom", it will automatically select the "F6|zoom" option for the recorder, and if the filename has "audiomonth", since it corresponds to more than one recorder option, it won't automatically select it, correct? Then for the parts that are not automatically selected, we go back and manually select them. All the other fields can be automatically tried to be extracted from the filename except for the DOI, name and note fields, so the DOI, name and note fields will need to be customized. How do we customize them, for example for name, we enter "{medium}-{site}-{during}-happy" into the name text box and all the uploaded files will be in the corresponding format as the value of name, for example "Air-Demo site-4000-happy" and "Water-Demo site2- 1800-happy", right? For csv upload metadata, do we need to extract it like above?

**Comment by LiuDilongNJ** [comment]
Or is my understanding above wrong and we should be extracting data from the properties of the file.

![Uploading image.png…]()

**Comment by kdarras** [comment]
Thanks for your questions Dilong. I edited the first post to give more details.

**Comment by kdarras** [comment]
It seems that it is not possible yet to set the tags of these WAV files:
![image](https://github.com/user-attachments/assets/f8801aff-deaf-4423-8721-d7d3a31937ee)
PS: don't use commas as thousands separators, please use spaces instead (more standard).
The "set note" button does not seem to do anything, so I am unsure...

**Comment by LiuDilongNJ** [comment]
Regarding metadata, it can read out a lot of arrays, and the arrays between different audio formats are different, such as bit rate. We need to set each audio format to read from a certain field. They are not interoperable. So we can only specify some data to match. And metadata seems to have many formats, such as BWF, ID3, iXML, RIFF, CART, XMP, etc. I think it is very messy.

**Comment by LiuDilongNJ** [comment]
Regarding the function of reading the date from the file, I modified it above the filename field. When we click it, the date will be automatically added to the field.
![image](https://github.com/user-attachments/assets/8b4bc071-ab06-455b-8204-7d669af15a42)
![image](https://github.com/user-attachments/assets/2ca29c3a-129b-4ac5-934c-6649c4cba978)

**Comment by LiuDilongNJ** [comment]
How can I solve this problem now? Should I restore them to the old version? Or do I need to make some changes?

**Comment by kdarras** [comment]
We can keep the new version, which allows users to batch-set and individually-set the recording table values at upload, prefix sound names, and view some metadata.

Sorry I did not notice the "set date" button. Please rename it to "Set date-time" and add the tooltip text that I wrote above with an info icon.

For the metadata, let's focus on displaying the most common metadata fields of [ID3 tags](https://www.exiftool.org/TagNames/ID3.html) at insertion and when viewing the recordings table:
- title
- artist
- album
- year
- comment
It should be clearly displayed above the corresponding table fields that these are ID3 tags.

**Comment by kdarras** [comment]
- I obtained the "Set date success" message with a single uploaded recording named BB3_custom.wav and no date-time was inserted. This is misleading. The message should be: "No date-time found in filename"

**Comment by kdarras** [comment]
Excellent - the metadata insertion works but let's wait for Stefan's reply today.

Adjustments needed:
- entered recording table values should persist: unfortunately, when adding more files, previously-entered data in the table fields are cleared
- ID3 tags (as far as I know, the only way to store metadata in WAVs) of WAV files generated by Audiomoths (a very common recorder) are not recognised. Here is a [sample recording](https://drive.google.com/file/d/1QclaUCksVbnOGM4er4EAG9nA1tIW_zaO/view?usp=sharing) and these are the metadata: 
![image](https://github.com/user-attachments/assets/fb6e61c3-4f2b-45c0-8223-568b1a59af4d)

**Comment by kdarras** [comment]
Excellent implementation.
Only two small adjustments to make (I don't need to re-test):
- change "Riff" to "RIFF"
- adapt the text of the existing resampling warning so that it reads: "Only the resampled recording will be stored on the server. The original metadata tags are not passed through to the new files." (Ideally, this warning should appear only when users check the box.)

Working in Docker

**Comment by kdarras** [comment]
Very pleasantly surprised that you we can see tags info of the pre-existing recordings in the recording table!
However, we need some details as to the implementation, because I cannot find these fields when accessing the table in phpMyAdmin, so it makes me wonder: are the metadata tags only read, and not saved into the recording table, as we decided earlier?
If this is the case, let's display these fields differently so it is clear the yare not actually stored in the database.

**Comment by LiuDilongNJ** [comment]
Yes the metadata is just read because a file may have more than one type of metadata and if it is stored in the database it will make the database structure more complex like adding a dozen or so new fields as it can be stored in the file so I think it is better to read them directly.

**Comment by kdarras** [comment]
OK, I did a final adjustment of the title and first post to clarify that we are only displaying metadata now.

The implementation with the non-editable fields and info icon is good. Please add a tooltip so that on mouse over the info icon, "Metadata tags read from the recording file" is shown. After this we should be done.

**Comment by kdarras** [comment]
note that the icon is missing from the pre-upload mask:
![image](https://github.com/user-attachments/assets/f635a066-7e59-4069-a961-7c6d2d136a0d)

**Comment by kdarras** [comment]
To solve the new problem mentioned above, I suggest to simplify the issue again.

We can avoid showing one line per uploaded recording after the upload and before insertion. We would only keep the table header to let the users specify the table fields in bulk, because:

1. apparently this breaks the upload functionality that previously worked well with >3000 files at once
2. it was not explicitly requested (although nice to have)
3. it is redundant with the single recording-level editing functionality that already exists when accessing the table after upload

Note:

- We show only the table fields that can be set by the user before database insertion (no need to show metadata tags, duration, etc.)
- we want to keep the prefixing functionality but it should be made clear that the filename follows after the prefix, maybe with a tooltip ("Name follows file name")
- the microphone must be selectable after selecting the recorder
- The table must be horizontally scrollable
- it is OK to keep the current design because it is consistent with the table view that follows the insertion of the files into the database

**Comment by kdarras** [comment]
OK we are back to the old upload form, no problem with that. An upload with 444 files just worked.

Small issues:
- Tooltips do not appear for the Sound name prefix (in the upload form) and the metadata fields (in the recording table).
- The microphone selection is not filtered anymore according to the recorder input (only in the recording table ,not the upload form):
![image](https://github.com/user-attachments/assets/0f090f81-a9b2-462f-8a63-3cb727c1f6c1)

Created #509 #510

**Comment by kdarras** [comment]
all bugs fixed and working online

**Comment by kdarras** [comment]
completed in #511
