### ISSUE TITLE
new fields in admin recordings management table

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#54]
Add user_id, recording_type and medium fields (#51) as well as existing note field to the table in the admin interface.

Make all new fields editable (user_id editable only for admins) and make sure they are all visible in the collections list view.

**Comment by kdarras** [comment]
It looks good, however, the user_id should be a drop-down showing the user names, not a text box.

**Comment by kdarras** [comment]
working in Docker. is it possible to have a drop-down menu for the users (but you could choose a hybrid drop-down with filter)?

**Comment by LiuDilongNJ** [comment]
I set it to a drop-down menu this time (we might take it as another issue for next contract to modify it to a hybrid drop-down with filter). In my opinion, the gadm, realm, etc. fields and the collection and project selection boxes in the upper left corner of the admin page both require the hybrid drop-down with filter.

**Comment by LiuDilongNJ** [comment]
In fact, the css form of the hybrid drop-down with filter has some conflicts with the tables, which doesn't display properly. I need some time to fix it.

**Comment by kdarras** [comment]
Yes, I actually already created a new issue before (#251 ). I will edit it now to add these fields that need it inside. Feel free to create a new issue for the CSS fix so we can plan future work realistically.

**Comment by kdarras** [comment]
working in Docker
