### ISSUE TITLE
Filter call types by selected taxon

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#67]
inside the tag creation and edition window, enable the call types selection drop-down only when the species has been selected, and filter it based on the selected taxon.
This is why I inserted new fields into the call_type table for assigning call types to taxa:
![Image](https://user-images.githubusercontent.com/7696198/188629414-6470e0c5-7199-4672-93a0-f8fa9a3b0bd1.png)
taxon_class refers to the Class of the species inside the species table. taxon_order refers to the order. Class contains orders. Both fields were needed because some sound/call types are specific to different taxonomic levels.

For instance, amphibia call types should only be shown when the selected species belongs to AMPHIBIA.

**Comment by kdarras** [comment]
I can only test this on production as there are no proper species data in the local version

**Comment by kdarras** [comment]
It seems that there are no call types appearing here:


![Image](https://user-images.githubusercontent.com/7696198/191986966-e8b27639-5f83-4ac9-9175-823da67036ec.png)

**Comment by LiuDilongNJ** [comment]
![image](https://user-images.githubusercontent.com/109188679/191999271-77418248-e103-472f-b9ca-e91ee2c988a5.png)
![image](https://user-images.githubusercontent.com/109188679/191999410-ae8fbf59-a7cb-4164-9c0c-a0c495e02f7c.png)
Test bird has an order value of Test Order and a class value of AVES. there is no match for it in sound_type.
It should be tested with Test primate. It has an order value of PRIMATA and a class value of MAMMALIA, and 10 data in sound_type will be displayed

![image](https://user-images.githubusercontent.com/109188679/192003840-af1c6ce3-ea29-4208-9023-947c5ab7ed12.png)
![image](https://user-images.githubusercontent.com/109188679/192004176-47281bc7-8b6f-4481-9270-0210d1acbde3.png)
When I delete the value of the taxon_order column, it loads type successfully
![image](https://user-images.githubusercontent.com/109188679/192004458-04a6e780-f795-4adb-93e6-933d0b59ff20.png)

**Comment by kdarras** [comment]
This should be coded a bit differently. The call types can apply to different levels.
If there is a matching class in the call types for the chosen species, these call types should be shown.
If there is a matching order in the call types for the chosen species, these call types should be shown.
the two should be independent. It's an OR relation.

**Comment by kdarras** [comment]
Sorry, it seems I need to clarify (my mistake), because the filtering does not work anymore for primates anymore (bats are shown too since they are mammals too).

It is a hierarchical OR relation :)

IF matching order exists, choose order to filter call types
ELSE IF matching class exists, choose class to filter call types

**Comment by kdarras** [comment]
working in Docker
