### ISSUE TITLE
review archival and display

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#71]
Allow reviewers to have only one active review of a tag, because it makes no sense if one user has multiple reviews.

If a reviewer submits a new review (this happens from time to time, when they change their mind), a dialog should appear to confirm that the previous review of the same user will be archived. Archival should log a date-time, and a user field logging who archived the review. The user should also be able to archive a review without submitting a new review, and apart from the creators of the reviews, only admins are allowed to archive other users' reviews.

When a tag's species is modified, all the reviews must be automatically archived, and the user field must be filled with the user name of the editor of the tag.

The reviews of one user are independent of the reviews of other users. Only admins should be allowed to see the reviews of all reviewers. Reviewers should not be able to view other reviewer's reviews (to avoid bias).

By default, archived reviews should not be visible in the review pane, but they can be displayed after clicking a button and should be shown as greyed out.

**Comment by LiuDilongNJ** [comment]
1. All users can only have one review in total.
2. If 1 is correct, how do I handle the old data with multiple reviews, taking the latest date?
3. users can archive review from other users
4. do we need a field to show who has archived the review?
5. when a tag is modified, a review is generated and shown as greyed out. we only record the status of the modification, not what was modified, right?

**Comment by kdarras** [comment]
Clarified first post.
1. one active review
2. see above
3. no
4. nice to have
5. only fill out the date-time and user name at arhival

**Comment by kdarras** [comment]
Currently, @LiuDilongNJ implemented having only one review per user per tag. This issue may be over-complicated and not needed anymore.
