### ISSUE TITLE
next tag button

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#85]
When reviewing, it is easy to get lost and lose time by switching back and forth between zoomed tags and the overview spectrogram.
Inside the tag window, we need buttons to go to the previous and the next tag, ordered by time (when times of tags are equal, start with the one that has the smallest tag ID). When clicking that button, the spectrogram should be shifted to zoom into the next tag.

**Comment by kdarras** [comment]
The next/previous buttons work well.
However, the spectrogram is not shifted/moved to the next tag.
Would it be possible to also make the tag window movable (by dragging with the mouse), so the user can see the spectrogram below? (tell me how much more time it would take)
No need to cycle through tags. When we reach the last tag, the "next" button should be greyed out. Same for the first tag: grey out the "previous" button.

**Comment by kdarras** [comment]
this works well now but it would be necessary to also save the tag contents before going to the next tag. Otherwise, it is not possible to edit or review tags in sequence (because the tag window is closed avec clicking "save") If you want, the buttons can be renamed "Save & Next", etc.

**Comment by kdarras** [comment]
tag window still closes after clicking "save", and the "next" button makes the window disappear when not logged in.

**Comment by LiuDilongNJ** [comment]
I have fixed it.

**Comment by kdarras** [comment]
Working in Docker

**Comment by LiuDilongNJ** [comment]
I'm going to fix it now.

**Comment by LiuDilongNJ** [comment]
![image](https://user-images.githubusercontent.com/109188679/218423884-ba4ec9b9-b603-45c6-bf94-12c2c5172888.png)
We can also close the window by clicking on the "X".
