### ISSUE TITLE
add button for uncompressed sound download

### ISSUE THREAD

**Issue by kdarras** [ecomontec/ecoSound-web#99]
Currently, the audio download button downloads compressed files (MP3, OGG, or FLAC for ultrasound). We should provide a WAV option as well, but ponder whether there should be bandwidth caps to avoid crashing the servers with potentially excessive behavior.
This button should be available inside the admin interface (recordings tab) and the utilities menu of the spectrogram player, but not for visitors.

**Comment by kdarras** [comment]
Clarification: project managers, since they have access to recordings and their meta-data, should be able to download recordings from the admin interface. Normal users, since they should only have access to their own tags and the tags that they have permissions for, would only be able to download individual recordings.

Note that for this is related to #342 as the download of multiple (zipped?) recordings should be allowed with this.

**Comment by kdarras** [comment]
Works in Docker. Would it be possible to zip the recordings into one file when multiple ones are selected?

**Comment by LiuDilongNJ** [comment]
Got it.

**Comment by kdarras** [comment]
I see. Then we could in fact disable the download button for multiple recordings, just like we disable the edit password button for multiple users)
We will implement proper processing queues for all actions that require a lot of resources (CNN execution, download, upload, etc.) properly in the future.

**Comment by kdarras** [comment]
works in Docker

**Comment by kdarras** [comment]
exporting recordings opens empty tab

**Comment by kdarras** [comment]
Clarification regarding the comment on Oct 10: non-logged-in visitors should not be able to download original recordings @LiuDilongNJ 
I edited the posts above for clarity
